namespace NPMAPI.Enums
{
    public enum eInboxHealthEvent
    {
        account_manager_created,
        attachment_created,
        attachment_updated,
        batched_in_collections_patient_ids,
        doctor_created,
        doctor_updated,
        enterprise_created,
        enterprise_payment_processed,
        enterprise_plan_changed,
        enterprise_plan_updated,
        enterprise_trial_will_end,
        enterprise_updated,
        invoice_created,
        invoice_payment_created,
        invoice_payment_updated,
        invoice_updated,
        line_item_created,
        line_item_updated,
        patient_billing_status_updated,
        patient_created,
        patient_merged,
        patient_payment_processed,
        patient_updated,
        payment_created,
        payment_updated,
        ticket_created,
        ticket_updated,
        write_off_created,
    }
}