//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NPMAPI.com.gatewayedi.services1 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EligibilitySoap", Namespace="GatewayEDI.WebServices")]
    public partial class Eligibility : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthSOAPHeader authSOAPHeaderValueField;
        
        private System.Threading.SendOrPostCallback DoInquiryOperationCompleted;
        
        private System.Threading.SendOrPostCallback DoInquiryByX12DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback DoInquiryByX12DataWith271ResponseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Eligibility() {
            this.Url = global::NPMAPI.Properties.Settings.Default.NPMAPI_com_gatewayedi_services1_Eligibility;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthSOAPHeader AuthSOAPHeaderValue {
            get {
                return this.authSOAPHeaderValueField;
            }
            set {
                this.authSOAPHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DoInquiryCompletedEventHandler DoInquiryCompleted;
        
        /// <remarks/>
        public event DoInquiryByX12DataCompletedEventHandler DoInquiryByX12DataCompleted;
        
        /// <remarks/>
        public event DoInquiryByX12DataWith271ResponseCompletedEventHandler DoInquiryByX12DataWith271ResponseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSOAPHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GatewayEDI.WebServices/DoInquiry", RequestNamespace="GatewayEDI.WebServices", ResponseNamespace="GatewayEDI.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSEligibilityResponse DoInquiry(WSEligibilityInquiry Inquiry) {
            object[] results = this.Invoke("DoInquiry", new object[] {
                        Inquiry});
            return ((WSEligibilityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DoInquiryAsync(WSEligibilityInquiry Inquiry) {
            this.DoInquiryAsync(Inquiry, null);
        }
        
        /// <remarks/>
        public void DoInquiryAsync(WSEligibilityInquiry Inquiry, object userState) {
            if ((this.DoInquiryOperationCompleted == null)) {
                this.DoInquiryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoInquiryOperationCompleted);
            }
            this.InvokeAsync("DoInquiry", new object[] {
                        Inquiry}, this.DoInquiryOperationCompleted, userState);
        }
        
        private void OnDoInquiryOperationCompleted(object arg) {
            if ((this.DoInquiryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoInquiryCompleted(this, new DoInquiryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSOAPHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GatewayEDI.WebServices/DoInquiryByX12Data", RequestNamespace="GatewayEDI.WebServices", ResponseNamespace="GatewayEDI.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSX12EligibilityResponse DoInquiryByX12Data(WSX12EligibilityInquiry Inquiry) {
            object[] results = this.Invoke("DoInquiryByX12Data", new object[] {
                        Inquiry});
            return ((WSX12EligibilityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DoInquiryByX12DataAsync(WSX12EligibilityInquiry Inquiry) {
            this.DoInquiryByX12DataAsync(Inquiry, null);
        }
        
        /// <remarks/>
        public void DoInquiryByX12DataAsync(WSX12EligibilityInquiry Inquiry, object userState) {
            if ((this.DoInquiryByX12DataOperationCompleted == null)) {
                this.DoInquiryByX12DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoInquiryByX12DataOperationCompleted);
            }
            this.InvokeAsync("DoInquiryByX12Data", new object[] {
                        Inquiry}, this.DoInquiryByX12DataOperationCompleted, userState);
        }
        
        private void OnDoInquiryByX12DataOperationCompleted(object arg) {
            if ((this.DoInquiryByX12DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoInquiryByX12DataCompleted(this, new DoInquiryByX12DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthSOAPHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GatewayEDI.WebServices/DoInquiryByX12DataWith271Response", RequestNamespace="GatewayEDI.WebServices", ResponseNamespace="GatewayEDI.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSX12EligibilityResponse DoInquiryByX12DataWith271Response(WSX12EligibilityInquiry Inquiry) {
            object[] results = this.Invoke("DoInquiryByX12DataWith271Response", new object[] {
                        Inquiry});
            return ((WSX12EligibilityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DoInquiryByX12DataWith271ResponseAsync(WSX12EligibilityInquiry Inquiry) {
            this.DoInquiryByX12DataWith271ResponseAsync(Inquiry, null);
        }
        
        /// <remarks/>
        public void DoInquiryByX12DataWith271ResponseAsync(WSX12EligibilityInquiry Inquiry, object userState) {
            if ((this.DoInquiryByX12DataWith271ResponseOperationCompleted == null)) {
                this.DoInquiryByX12DataWith271ResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoInquiryByX12DataWith271ResponseOperationCompleted);
            }
            this.InvokeAsync("DoInquiryByX12DataWith271Response", new object[] {
                        Inquiry}, this.DoInquiryByX12DataWith271ResponseOperationCompleted, userState);
        }
        
        private void OnDoInquiryByX12DataWith271ResponseOperationCompleted(object arg) {
            if ((this.DoInquiryByX12DataWith271ResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoInquiryByX12DataWith271ResponseCompleted(this, new DoInquiryByX12DataWith271ResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GatewayEDI.WebServices")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="GatewayEDI.WebServices", IsNullable=false)]
    public partial class AuthSOAPHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GatewayEDI.WebServices")]
    public partial class WSX12EligibilityResponse {
        
        private string responseAsRawStringField;
        
        private string responseAsXmlField;
        
        private ValidationFailureCollection extraProcessingInfoField;
        
        private SuccessCode successCodeField;
        
        private WSX12EligibilityInquiry originalInquiryField;
        
        /// <remarks/>
        public string ResponseAsRawString {
            get {
                return this.responseAsRawStringField;
            }
            set {
                this.responseAsRawStringField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseAsXml {
            get {
                return this.responseAsXmlField;
            }
            set {
                this.responseAsXmlField = value;
            }
        }
        
        /// <remarks/>
        public ValidationFailureCollection ExtraProcessingInfo {
            get {
                return this.extraProcessingInfoField;
            }
            set {
                this.extraProcessingInfoField = value;
            }
        }
        
        /// <remarks/>
        public SuccessCode SuccessCode {
            get {
                return this.successCodeField;
            }
            set {
                this.successCodeField = value;
            }
        }
        
        /// <remarks/>
        public WSX12EligibilityInquiry OriginalInquiry {
            get {
                return this.originalInquiryField;
            }
            set {
                this.originalInquiryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GatewayEDI.WebServices")]
    public partial class ValidationFailureCollection {
        
        private string[] allMessagesField;
        
        private ValidationFailure[] failuresField;
        
        /// <remarks/>
        public string[] AllMessages {
            get {
                return this.allMessagesField;
            }
            set {
                this.allMessagesField = value;
            }
        }
        
        /// <remarks/>
        public ValidationFailure[] Failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GatewayEDI.WebServices")]
    public partial class ValidationFailure {
        
        private string[] affectedFieldsField;
        
        private string messageField;
        
        /// <remarks/>
        public string[] AffectedFields {
            get {
                return this.affectedFieldsField;
            }
            set {
                this.affectedFieldsField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GatewayEDI.WebServices")]
    public enum SuccessCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        ValidationFailure,
        
        /// <remarks/>
        PayerTimeout,
        
        /// <remarks/>
        PayerNotSupported,
        
        /// <remarks/>
        SystemError,
        
        /// <remarks/>
        PayerEnrollmentRequired,
        
        /// <remarks/>
        ProviderEnrollmentRequired,
        
        /// <remarks/>
        ProductRequired,
        
        /// <remarks/>
        QuantityExceeded,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GatewayEDI.WebServices")]
    public partial class WSX12EligibilityInquiry {
        
        private string x12InputField;
        
        private string gediPayerIDField;
        
        private WSResponseDataType responseDataTypeField;
        
        /// <remarks/>
        public string X12Input {
            get {
                return this.x12InputField;
            }
            set {
                this.x12InputField = value;
            }
        }
        
        /// <remarks/>
        public string GediPayerID {
            get {
                return this.gediPayerIDField;
            }
            set {
                this.gediPayerIDField = value;
            }
        }
        
        /// <remarks/>
        public WSResponseDataType ResponseDataType {
            get {
                return this.responseDataTypeField;
            }
            set {
                this.responseDataTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GatewayEDI.WebServices")]
    public enum WSResponseDataType {
        
        /// <remarks/>
        Xml,
        
        /// <remarks/>
        RawPayerData,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GatewayEDI.WebServices")]
    public partial class WSEligibilityResponse {
        
        private string responseAsRawStringField;
        
        private string responseAsXmlField;
        
        private ValidationFailureCollection extraProcessingInfoField;
        
        private SuccessCode successCodeField;
        
        private WSEligibilityInquiry originalInquiryField;
        
        /// <remarks/>
        public string ResponseAsRawString {
            get {
                return this.responseAsRawStringField;
            }
            set {
                this.responseAsRawStringField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseAsXml {
            get {
                return this.responseAsXmlField;
            }
            set {
                this.responseAsXmlField = value;
            }
        }
        
        /// <remarks/>
        public ValidationFailureCollection ExtraProcessingInfo {
            get {
                return this.extraProcessingInfoField;
            }
            set {
                this.extraProcessingInfoField = value;
            }
        }
        
        /// <remarks/>
        public SuccessCode SuccessCode {
            get {
                return this.successCodeField;
            }
            set {
                this.successCodeField = value;
            }
        }
        
        /// <remarks/>
        public WSEligibilityInquiry OriginalInquiry {
            get {
                return this.originalInquiryField;
            }
            set {
                this.originalInquiryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GatewayEDI.WebServices")]
    public partial class WSEligibilityInquiry {
        
        private MyNameValue[] parametersField;
        
        private WSResponseDataType responseDataTypeField;
        
        /// <remarks/>
        public MyNameValue[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        public WSResponseDataType ResponseDataType {
            get {
                return this.responseDataTypeField;
            }
            set {
                this.responseDataTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GatewayEDI.WebServices")]
    public partial class MyNameValue {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DoInquiryCompletedEventHandler(object sender, DoInquiryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoInquiryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoInquiryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSEligibilityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSEligibilityResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DoInquiryByX12DataCompletedEventHandler(object sender, DoInquiryByX12DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoInquiryByX12DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoInquiryByX12DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSX12EligibilityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSX12EligibilityResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DoInquiryByX12DataWith271ResponseCompletedEventHandler(object sender, DoInquiryByX12DataWith271ResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoInquiryByX12DataWith271ResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoInquiryByX12DataWith271ResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSX12EligibilityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSX12EligibilityResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591