//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGING_SUMMARY_PATIENT_REPORT
    {
        public string INSPAYER_DESCRIPTION { get; set; }
        public string C0_30 { get; set; }
        public Nullable<decimal> C31_60 { get; set; }
        public Nullable<decimal> C61_90 { get; set; }
        public Nullable<decimal> C91_120 { get; set; }
        public Nullable<decimal> C121_150 { get; set; }
        public Nullable<decimal> C151_180 { get; set; }
        public Nullable<decimal> C180_PLUS { get; set; }
        public int PRACTICE_CODE { get; set; }
    }
}
