//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long Appointment_Id { get; set; }
        public long Provider_Code { get; set; }
        public long Patient_Account { get; set; }
        public Nullable<long> Reason_Id { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Appointment_Date_Time { get; set; }
        public Nullable<int> Appointment_Status_Id { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public Nullable<long> Location_Id { get; set; }
        public Nullable<int> Appointment_Units { get; set; }
        public string Time_From { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> IsBreakTime { get; set; }
        public Nullable<bool> IsMeetingTime { get; set; }
        public string Temp_time_from { get; set; }
        public Nullable<long> Duration { get; set; }
        public Nullable<long> Attending_Physician { get; set; }
        public Nullable<bool> Is_NewPatient_Appointment { get; set; }
        public Nullable<int> Noshow_charges { get; set; }
        public Nullable<decimal> Amountcollected { get; set; }
        public Nullable<decimal> Previous_Balance { get; set; }
        public string eligibilityColor { get; set; }
    }
}
