//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchPatientClaim
    {
        public long BatchPatientClaimId { get; set; }
        public long BatchNo { get; set; }
        public long ClaimNo { get; set; }
    }
}
