//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCHPAYMENT
    {
        public long BatchNo { get; set; }
        public Nullable<long> InsuranceID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public string CheckNo { get; set; }
        public Nullable<System.DateTimeOffset> CheckDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> FacilityID { get; set; }
        public Nullable<System.DateTimeOffset> EOBDate { get; set; }
        public Nullable<System.DateTimeOffset> DepositDate { get; set; }
        public Nullable<System.DateTimeOffset> ReceivedDate { get; set; }
        public string NOtes { get; set; }
        public Nullable<long> PatientAccount { get; set; }
        public string PatientName { get; set; }
        public Nullable<decimal> PostedAmount { get; set; }
        public string practice_code { get; set; }
    }
}
