//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claims_bkp_10012019
    {
        public long Claim_No { get; set; }
        public Nullable<long> Patient_Account { get; set; }
        public Nullable<System.DateTimeOffset> Bill_Date { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<long> Location_Code { get; set; }
        public Nullable<long> Attending_Physician { get; set; }
        public Nullable<long> Billing_Physician { get; set; }
        public Nullable<long> Supervising_Physician { get; set; }
        public Nullable<long> Referring_Physician { get; set; }
        public string PA_Number { get; set; }
        public string Referral_Number { get; set; }
        public string ICN_Number { get; set; }
        public Nullable<long> Facility_Code { get; set; }
        public Nullable<System.DateTime> Hospital_From { get; set; }
        public Nullable<System.DateTime> Hospital_To { get; set; }
        public string Pri_Status { get; set; }
        public string Sec_Status { get; set; }
        public string Oth_Status { get; set; }
        public string Pat_Status { get; set; }
        public Nullable<long> Attach_Type_Code { get; set; }
        public string Claim_Status { get; set; }
        public Nullable<System.DateTime> Claim_Status_Date { get; set; }
        public string Current_Visit { get; set; }
        public string Allowed_Visit { get; set; }
        public Nullable<bool> Accident_Auto { get; set; }
        public Nullable<bool> Accident_Other { get; set; }
        public Nullable<bool> Employment { get; set; }
        public Nullable<bool> Accident_Emergency { get; set; }
        public Nullable<bool> Accident_Time { get; set; }
        public Nullable<System.DateTime> Accident_Date { get; set; }
        public string Accident_State { get; set; }
        public string Spinal_Manipulation_Condition_Code { get; set; }
        public string Spinal_Manipulation_Description { get; set; }
        public Nullable<bool> Spinal_Manipulation_Xray_Availability { get; set; }
        public string Phy_Exam_Code { get; set; }
        public string Phy_Exam_Desc { get; set; }
        public Nullable<System.DateTime> Start_Care_Date { get; set; }
        public Nullable<System.DateTime> Last_Seen_Date { get; set; }
        public Nullable<System.DateTime> Current_Illness_Date { get; set; }
        public Nullable<System.DateTime> X_Ray_Date { get; set; }
        public Nullable<decimal> Pri_Ins_Payment { get; set; }
        public Nullable<decimal> Sec_Ins_Payment { get; set; }
        public Nullable<decimal> Oth_Ins_Payment { get; set; }
        public Nullable<decimal> Patient_Payment { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public Nullable<decimal> Amt_Due { get; set; }
        public Nullable<decimal> Amt_Paid { get; set; }
        public Nullable<decimal> Claim_Total { get; set; }
        public string DX_Code1 { get; set; }
        public string DX_Code2 { get; set; }
        public string DX_Code3 { get; set; }
        public string DX_Code4 { get; set; }
        public string DX_Code5 { get; set; }
        public string DX_Code6 { get; set; }
        public string DX_Code7 { get; set; }
        public string DX_Code8 { get; set; }
        public string DX_Code9 { get; set; }
        public string DX_Code10 { get; set; }
        public string DX_Code11 { get; set; }
        public string DX_Code12 { get; set; }
        public Nullable<byte> AA { get; set; }
        public string BLOCK1213 { get; set; }
        public string Pos { get; set; }
        public Nullable<System.DateTime> REBILL_DATE { get; set; }
        public Nullable<bool> PTL_Status { get; set; }
        public string Delay_Reason_Code { get; set; }
        public Nullable<System.DateTime> Ref_Date { get; set; }
        public Nullable<bool> Add_CLIA_Number { get; set; }
        public string Special_Program_Code { get; set; }
        public Nullable<bool> Print_Center { get; set; }
        public Nullable<System.DateTime> Injury_Date { get; set; }
        public Nullable<System.DateTime> Injury_Time { get; set; }
        public string Epsdt_Services { get; set; }
        public string HCFA_Note { get; set; }
        public Nullable<bool> Patient_Payment_Plan { get; set; }
        public Nullable<bool> Patient_Statement { get; set; }
        public Nullable<bool> Include_In_Sdf { get; set; }
        public Nullable<bool> Is_Self_Pay { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public string scan_no { get; set; }
        public Nullable<bool> resolve { get; set; }
        public string Reference_Number { get; set; }
        public Nullable<System.DateTime> Scan_Date { get; set; }
        public Nullable<long> Ordering_Physician { get; set; }
        public Nullable<byte> Response_Code { get; set; }
        public string Condition_Code { get; set; }
        public string Reference_Claim_No { get; set; }
        public Nullable<System.DateTime> EDC_date { get; set; }
        public string Institution_Condition_Code { get; set; }
        public string SpecialProgramCode { get; set; }
        public string ServiceAuthExceptionCode { get; set; }
        public string Map_Claim_History { get; set; }
        public Nullable<System.DateTime> LMP_Date { get; set; }
        public Nullable<System.DateTime> SCAN_DATE_PTL { get; set; }
        public string PAGE_NO { get; set; }
        public string Weight { get; set; }
        public string Transport_Distance { get; set; }
        public string Transportation_Reason_Code { get; set; }
        public string Transportation_Condition_Code { get; set; }
        public string Transport_Code { get; set; }
        public string Condition_Indicator { get; set; }
        public Nullable<bool> Archive { get; set; }
        public Nullable<bool> Arbitration { get; set; }
        public Nullable<long> Last_Seen_Physician { get; set; }
        public Nullable<bool> Is_Draft { get; set; }
        public Nullable<long> Draft_Patient_Account { get; set; }
        public Nullable<bool> Copay_Owed { get; set; }
        public Nullable<bool> Copay_Waived { get; set; }
        public Nullable<System.DateTime> Manifestation_Date { get; set; }
        public Nullable<System.DateTime> ASSUMED_CARE_DATE { get; set; }
        public Nullable<System.DateTime> RELINQISHED_CARE_DATE { get; set; }
        public Nullable<long> Claims_Status_Code { get; set; }
        public string Coded_By { get; set; }
        public Nullable<System.DateTime> TCM_Cal_Dos { get; set; }
        public Nullable<bool> Stop_Submission { get; set; }
        public Nullable<bool> Additional_Estatement { get; set; }
        public Nullable<System.DateTime> Last_statement_Sent_date { get; set; }
        public Nullable<System.DateTime> Last_Work_Date { get; set; }
        public string BATCH_NO { get; set; }
        public Nullable<System.DateTime> Batch_Date { get; set; }
        public Nullable<long> Plan_Code { get; set; }
        public string Linked_Claims { get; set; }
        public Nullable<bool> Authorization_Req { get; set; }
        public string PROMISED_AMT_WAIVE { get; set; }
        public Nullable<System.DateTime> PROMISED_AMT_WAIVE_DATE { get; set; }
        public string PROMISED_AMT_WAIVE_BY { get; set; }
        public Nullable<decimal> PROMISED_AMT { get; set; }
        public Nullable<System.DateTime> PROMISED_AMT_DATE { get; set; }
        public string PROMISED_AMT_ENTERED_BY { get; set; }
        public Nullable<long> DWC_ID { get; set; }
        public Nullable<long> DWC_DETAIL_ID { get; set; }
        public Nullable<bool> Advance_Pat_Payment { get; set; }
        public Nullable<long> PA_TRACKING_ID { get; set; }
        public string Created_From { get; set; }
        public string Modified_From { get; set; }
        public Nullable<long> practice_code { get; set; }
        public string Luo { get; set; }
        public Nullable<bool> is_resubmitted { get; set; }
        public Nullable<bool> Is_Corrected { get; set; }
    }
}
