//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim_Payments
    {
        public long claim_payments_id { get; set; }
        public long Claim_No { get; set; }
        public int Payment_No { get; set; }
        public string Payment_Type { get; set; }
        public string Payment_Source { get; set; }
        public Nullable<System.DateTimeOffset> Date_Entry { get; set; }
        public Nullable<System.DateTimeOffset> Date_Adj_Payment { get; set; }
        public Nullable<System.DateTime> Date_Filing { get; set; }
        public Nullable<decimal> Amount_Approved { get; set; }
        public Nullable<decimal> Amount_Paid { get; set; }
        public string Adj_Write_Off_Type { get; set; }
        public Nullable<decimal> Amount_Adjusted { get; set; }
        public string Details { get; set; }
        public string Reject_Type { get; set; }
        public Nullable<decimal> Reject_Amount { get; set; }
        public string Paid_Proc_Code { get; set; }
        public string Charged_Proc_Code { get; set; }
        public Nullable<int> Units { get; set; }
        public Nullable<long> Insurance_Id { get; set; }
        public string Check_No { get; set; }
        public Nullable<System.DateTime> Cheque_Date { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string EOB_CODE { get; set; }
        public string ERA_CATEGORY_CODE { get; set; }
        public string ERA_ADJUSTMENT_CODE { get; set; }
        public string ICN { get; set; }
        public string ERA_Rejection_CATEGORY_CODE { get; set; }
        public string MODI_CODE1 { get; set; }
        public string MODI_CODE2 { get; set; }
        public string ENTERED_FROM { get; set; }
        public Nullable<int> Sequence_No { get; set; }
        public Nullable<decimal> Contractual_Amt { get; set; }
        public string BATCH_NO { get; set; }
        public Nullable<System.DateTime> BATCH_DATE { get; set; }
        public Nullable<long> DEPOSITSLIP_ID { get; set; }
        public Nullable<bool> IsRectify { get; set; }
        public string modified_from { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<System.DateTime> Dos_From { get; set; }
        public Nullable<System.DateTime> Dos_To { get; set; }
    }
}
