//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimStatus_Search_Criteria
    {
        public long ID { get; set; }
        public string Payer_ID { get; set; }
        public string Payer_Level { get; set; }
        public Nullable<int> Search_Field1 { get; set; }
        public Nullable<int> Search_Field2 { get; set; }
        public Nullable<int> Search_Field3 { get; set; }
        public Nullable<int> Search_Field4 { get; set; }
        public Nullable<int> Search_Field5 { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> Prority_Level { get; set; }
    }
}
