//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claims_filling_limit
    {
        public long CFL_ID { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public string Practice_Name { get; set; }
        public string Patient_Name { get; set; }
        public Nullable<long> Claim_no { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<int> Claim_Total { get; set; }
        public Nullable<decimal> Amount_Due { get; set; }
        public string Payer_Name { get; set; }
        public string Pri_Status { get; set; }
        public string Claim_Last_Submission { get; set; }
        public Nullable<int> Aging_from_Last_submission { get; set; }
        public Nullable<int> Limit_Count { get; set; }
        public Nullable<int> Filing_Count_Down { get; set; }
        public string Team_Lead { get; set; }
        public string MO { get; set; }
        public string Resolved_By { get; set; }
        public Nullable<System.DateTime> Resolved_Date { get; set; }
        public Nullable<bool> Resolved { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string REMARKS { get; set; }
    }
}
