//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim_Status_Codes
    {
        public long S_No { get; set; }
        public string STATUS_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> REJECTED { get; set; }
    }
}
