//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAIMS_SUBMITTED
    {
        public long S_no { get; set; }
        public Nullable<long> Patient_Account { get; set; }
        public Nullable<long> Claim_No { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<System.DateTimeOffset> Bill_Date { get; set; }
        public Nullable<long> Att_Physician { get; set; }
        public Nullable<decimal> Amt_Due { get; set; }
        public Nullable<decimal> Claim_Total { get; set; }
        public Nullable<long> Insurance_Id { get; set; }
        public string Policy_Number { get; set; }
        public string Pri_Status { get; set; }
        public string Sec_Status { get; set; }
        public string Oth_Status { get; set; }
        public string Pat_Status { get; set; }
        public Nullable<System.DateTimeOffset> Process_Date { get; set; }
        public string Claim_Status { get; set; }
        public string Submission_Type { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Sent_File { get; set; }
        public string First_Lvl_Ack_File { get; set; }
        public string First_Lvl_Results { get; set; }
        public string Second_lvl_ack_file { get; set; }
        public string Second_lvl_results { get; set; }
        public string Sent_St_Value { get; set; }
        public string Sent_IEA_Value { get; set; }
        public string Receiver_id { get; set; }
        public string Submitter_id { get; set; }
        public string Payer_id { get; set; }
        public string First_lvl_Rejection_Reason { get; set; }
        public string Second_lvl_Rejection_Reason { get; set; }
        public Nullable<System.DateTime> REJECTION_DATE { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTimeOffset> CREATED_Date { get; set; }
        public string Submission_Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> Plan_ID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Sent_GS_Value { get; set; }
        public Nullable<int> POS { get; set; }
        public string Pri_Sec_Oth_Type { get; set; }
        public string Submitted_DX_Codes { get; set; }
        public string Submitted_Proc_Codes { get; set; }
        public string Sent_837_Data { get; set; }
        public string Insurance_File_Id { get; set; }
        public Nullable<long> Billing_Physician { get; set; }
        public string Billing_Prov_Npi { get; set; }
        public Nullable<long> Submission_Setup_Id { get; set; }
        public string Provider_Name { get; set; }
        public string Patient_Name { get; set; }
    }
}
