//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim_batch
    {
        public long batch_id { get; set; }
        public string batch_name { get; set; }
        public Nullable<long> provider_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> file_generated { get; set; }
        public string file_path { get; set; }
        public string downloaded_by { get; set; }
        public Nullable<System.DateTime> downloaded_date { get; set; }
        public Nullable<long> practice_id { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<long> created_user { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<long> modified_user { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.DateTime> client_date_created { get; set; }
        public Nullable<System.DateTime> client_date_modified { get; set; }
        public string system_ip { get; set; }
        public Nullable<bool> batch_lock { get; set; }
        public string batch_status { get; set; }
        public Nullable<System.DateTime> date_uploaded { get; set; }
        public Nullable<long> uploaded_user { get; set; }
        public Nullable<System.DateTime> date_processed { get; set; }
        public string response_file_path { get; set; }
        public string batch_status_detail { get; set; }
        public string batch_type { get; set; }
        public string Batch_Status999 { get; set; }
    }
}
