//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim_reject_type_CO
    {
        public long practicE_code { get; set; }
        public long claim_no { get; set; }
        public long claim_payments_id { get; set; }
        public string reject_type { get; set; }
    }
}
