//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim_batch_error
    {
        public long id { get; set; }
        public Nullable<long> patient_id { get; set; }
        public Nullable<long> claim_id { get; set; }
        public Nullable<System.DateTime> dos { get; set; }
        public string error { get; set; }
        public string patient_name { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<long> created_user { get; set; }
        public string error_type { get; set; }
        public Nullable<bool> ignore_error { get; set; }
        public string ignore_by { get; set; }
        public Nullable<System.DateTime> ignore_date { get; set; }
        public Nullable<long> batch_id { get; set; }
    }
}
