//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim_Worker_Injurycase
    {
        public decimal claim_no { get; set; }
        public string service_status { get; set; }
        public string vfbl_vawbl_status { get; set; }
        public Nullable<System.DateTime> claim_resubmitted_date { get; set; }
        public string pre_existing_injury { get; set; }
        public Nullable<System.DateTime> first_treatment_date { get; set; }
        public string medical_improvement_status { get; set; }
        public Nullable<System.DateTime> medical_improvement_date { get; set; }
        public string planned_future_treatment { get; set; }
        public string x_ray_status { get; set; }
        public string authorization_status { get; set; }
        public string authorization_description { get; set; }
        public string injury_result_status { get; set; }
        public string injury_result_description { get; set; }
        public Nullable<System.DateTime> disability_date { get; set; }
        public string patient_working_status { get; set; }
        public string regular_duty_status { get; set; }
        public string regular_duty_description { get; set; }
        public string type_work_status { get; set; }
        public string initial_treatment { get; set; }
        public string physician_type { get; set; }
        public string body_percentage { get; set; }
        public string type_work_description { get; set; }
    }
}
