//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim_Charges
    {
        public long claim_charges_id { get; set; }
        public long Claim_No { get; set; }
        public int Sequence_No { get; set; }
        public string Procedure_Code { get; set; }
        public Nullable<System.DateTime> DOE { get; set; }
        public Nullable<System.DateTime> Dos_From { get; set; }
        public Nullable<System.DateTime> Dos_To { get; set; }
        public Nullable<int> POS { get; set; }
        public Nullable<int> DX_Pointer1 { get; set; }
        public Nullable<int> DX_Pointer2 { get; set; }
        public Nullable<int> DX_Pointer3 { get; set; }
        public Nullable<int> DX_Pointer4 { get; set; }
        public string Modi_Code1 { get; set; }
        public string Modi_Code2 { get; set; }
        public string Modi_Code3 { get; set; }
        public string Modi_Code4 { get; set; }
        public Nullable<int> Units { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> Include_In_Edi { get; set; }
        public Nullable<bool> Include_In_Sdf { get; set; }
        public string Unit_Time_Day { get; set; }
        public Nullable<bool> PTL_Status { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> Stop_Time { get; set; }
        public string Drug_Code { get; set; }
        public string Revenue_Code { get; set; }
        public string Weight { get; set; }
        public string Transport_Distance { get; set; }
        public string Transportation_Reason_Code { get; set; }
        public string Transportation_Condition_Code { get; set; }
        public string Transport_Code { get; set; }
        public string Condition_Indicator { get; set; }
        public string Notes { get; set; }
        public Nullable<double> NDC_Quantity { get; set; }
        public string NDC_Qualifier { get; set; }
        public string NDC_Service_Description { get; set; }
        public Nullable<decimal> Contractual_Amt { get; set; }
        public string Emergency_Related { get; set; }
        public Nullable<bool> IsRectify { get; set; }
        public string Accession_No { get; set; }
        public string Batch_No { get; set; }
        public Nullable<System.DateTime> Batch_Date { get; set; }
        public string Cpt_Type { get; set; }
        public Nullable<bool> Authorized_Cpt { get; set; }
        public Nullable<decimal> Actual_amount { get; set; }
        public Nullable<bool> Pointer_Flag { get; set; }
        public Nullable<bool> is_resubmitted { get; set; }
        public string Physical_Modifier { get; set; }
    }
}
