//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claims_ICD10DX
    {
        public long Claim_no { get; set; }
        public string ICD10DX1 { get; set; }
        public string ICD10DX2 { get; set; }
        public string ICD10DX3 { get; set; }
        public string ICD10DX4 { get; set; }
        public string ICD10DX5 { get; set; }
        public string ICD10DX6 { get; set; }
        public string ICD10DX7 { get; set; }
        public string ICD10DX8 { get; set; }
        public string ICD10DX9 { get; set; }
        public string ICD10DX10 { get; set; }
        public string ICD10DX11 { get; set; }
        public string ICD10DX12 { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
    }
}
