//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLC_Roles
    {
        public long CLC_Role_Id { get; set; }
        public string CLC_Role_Description { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
