//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contractor
    {
        public int contractor_id { get; set; }
        public int contractor_type_id { get; set; }
        public int contractor_version { get; set; }
        public string contractor_name { get; set; }
        public string contractor_bus_name { get; set; }
        public string contractor_number { get; set; }
        public int consortium_id { get; set; }
        public int oversight_rgn { get; set; }
        public Nullable<int> dmerc_rgn { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string city { get; set; }
        public Nullable<int> state_id { get; set; }
        public string zipcode { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string status { get; set; }
        public System.DateTime last_updated { get; set; }
        public string url { get; set; }
    }
}
