//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contractor_jurisdiction
    {
        public int contractor_id { get; set; }
        public int contractor_type_id { get; set; }
        public int contractor_version { get; set; }
        public int state_id { get; set; }
        public System.DateTime last_updated { get; set; }
    }
}
