//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coverage_topic_lookup
    {
        public int coverage_topic_id { get; set; }
        public int coverage_topic_version { get; set; }
        public string description { get; set; }
        public System.DateTime last_updated { get; set; }
        public Nullable<int> sort_order { get; set; }
    }
}
