//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPADASHBOARD
    {
        public string TYPE { get; set; }
        public Nullable<decimal> OCT_2018 { get; set; }
        public Nullable<decimal> NOV_2018 { get; set; }
        public Nullable<decimal> DEC_2018 { get; set; }
        public Nullable<decimal> JAN_2019 { get; set; }
        public Nullable<decimal> FEB_2019 { get; set; }
    }
}
