//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPT_Fee_Charge
    {
        public int S_No { get; set; }
        public string Practice_Code { get; set; }
        public string prac_state { get; set; }
        public string procedure_code { get; set; }
        public string Old_Charges { get; set; }
        public string Revised_Charges { get; set; }
        public string Changes_Made_In_Plan { get; set; }
        public string Date_Of_Charges_Change { get; set; }
    }
}
