//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPT_HOSPBILLS
    {
        public long ID { get; set; }
        public Nullable<long> PRACTICE_CODE { get; set; }
        public string PROC_CODE { get; set; }
        public decimal FEE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string ISREPLICATED { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
