//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPT_FEE_STRUCTURE
    {
        public long practice_code { get; set; }
        public string prac_state { get; set; }
        public string prac_name { get; set; }
        public long inspayer_id { get; set; }
        public string InsPayer_Description { get; set; }
        public string CPT_code { get; set; }
        public string modifier { get; set; }
        public Nullable<int> cnt { get; set; }
        public string proc_description { get; set; }
        public string cpt_modifier { get; set; }
        public Nullable<decimal> FNPF { get; set; }
        public Nullable<decimal> NFNPF { get; set; }
        public Nullable<decimal> NFPF { get; set; }
        public Nullable<decimal> FPF { get; set; }
        public string cpt_plan { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    }
}
