//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customised_Procedure_Description
    {
        public string Proc_Code { get; set; }
        public string Description { get; set; }
        public Nullable<long> Practice_code { get; set; }
    }
}
