//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField
    {
        public string OwnerID { get; set; }
        public string Name { get; set; }
        public string EntityType { get; set; }
        public string EntityRefListID { get; set; }
        public string OtherType { get; set; }
        public string Value { get; set; }
    }
}
