//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_Scrubber_Rules
    {
        public long Edit_id { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public Nullable<long> Gc_id { get; set; }
        public string Entity1 { get; set; }
        public string Field1 { get; set; }
        public string Operator { get; set; }
        public string Value { get; set; }
        public string Entity2 { get; set; }
        public string Field2 { get; set; }
        public string Condition { get; set; }
        public string ErrorMessage { get; set; }
        public string Edit_Name { get; set; }
        public string Edit_Description { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
