//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Default_Setting_Practice
    {
        public long Practice_code { get; set; }
        public Nullable<long> Provider_code { get; set; }
        public Nullable<long> Location_code { get; set; }
        public string user_type { get; set; }
        public Nullable<bool> IS_AVAILABLE_TIME_SLOT { get; set; }
    }
}
