//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPOSIT_SLIPS
    {
        public long DS_ID { get; set; }
        public Nullable<System.DateTime> DS_DATE { get; set; }
        public Nullable<long> BANK_Code { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string No_ofEnteries { get; set; }
        public Nullable<decimal> chk_Amt { get; set; }
        public Nullable<decimal> T_Amount { get; set; }
        public string Enteries_Status { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public string Slip_Number { get; set; }
        public Nullable<long> Location_Code { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> practicE_code { get; set; }
        public Nullable<long> Statement_Id { get; set; }
    }
}
