//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit_Bank
    {
        public int Bank_Id { get; set; }
        public string Bank_Name { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public Nullable<long> Bank_Detail_Id { get; set; }
        public string Account_Number { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> Bank_Statement_Date { get; set; }
        public Nullable<decimal> Opening_Balance { get; set; }
        public Nullable<decimal> Closing_Balance { get; set; }
        public Nullable<decimal> Bank_Statement_Balance { get; set; }
    }
}
