//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deposit
    {
        public long DWC_DepositSlip_ID { get; set; }
        public Nullable<long> DWC_Id { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public string Payment_Method { get; set; }
        public Nullable<long> Insurance_id { get; set; }
        public string check_No { get; set; }
        public string Paid_Amount { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<long> Location_Code { get; set; }
        public string REASON { get; set; }
        public string PAYMENT_SOURCE { get; set; }
        public string PAYMENT_TYPE { get; set; }
        public string BATCH_NO { get; set; }
        public Nullable<System.DateTime> BATCH_DATE { get; set; }
    }
}
