//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeptShiftTiming
    {
        public long DeptShift_ID { get; set; }
        public long Department { get; set; }
        public long Shift { get; set; }
        public long Office { get; set; }
        public System.DateTime Time_To { get; set; }
        public System.DateTime Time_From { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string SALARY_TYPE { get; set; }
    }
}
