//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosi
    {
        public string Diag_Code { get; set; }
        public string Diag_Description { get; set; }
        public string Gender_Applied_On { get; set; }
        public string Age_Category { get; set; }
        public string Age_Range_Criteria { get; set; }
        public Nullable<int> Age_From { get; set; }
        public Nullable<int> Age_To { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public Nullable<System.DateTime> Diag_Effective_Date { get; set; }
        public Nullable<System.DateTime> Diag_Expiry_Date { get; set; }
        public string Diag_Replacement_Codes { get; set; }
        public Nullable<bool> Recent { get; set; }
        public Nullable<System.DateTime> Recent_Date { get; set; }
        public string Diag_Type { get; set; }
        public Nullable<bool> Critical_DX_Code { get; set; }
        public string ICD_version { get; set; }
    }
}
