//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSIS_PAYER
    {
        public long Diagnosis_PayerId { get; set; }
        public string Payer_Id { get; set; }
        public Nullable<bool> Start_Care_Date { get; set; }
        public Nullable<bool> Last_Seen_Date { get; set; }
        public Nullable<bool> Current_Illness { get; set; }
        public Nullable<bool> LMP_Dates { get; set; }
        public string Diagnosis_Code { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Payer_Description { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
