//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diff_claim_totals
    {
        public long CLAIM_NO { get; set; }
        public Nullable<decimal> PRI_INS_PAYMENT { get; set; }
        public decimal detail_prim_payments { get; set; }
        public Nullable<decimal> SEC_INS_PAYMENT { get; set; }
        public decimal detail_sec_payments { get; set; }
        public Nullable<decimal> OTH_INS_PAYMENT { get; set; }
        public decimal detail_oth_payments { get; set; }
        public Nullable<decimal> patient_PAYMENT { get; set; }
        public decimal detail_pt_payments { get; set; }
        public Nullable<decimal> adjustment { get; set; }
        public decimal detail_adj_payments { get; set; }
    }
}
