//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO
    {
        public int ID1 { get; set; }
        public Nullable<int> ID { get; set; }
        public string Patient_account { get; set; }
        public Nullable<decimal> claim_no { get; set; }
        public Nullable<System.DateTime> dos { get; set; }
    }
}
