//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_CATEGORIES
    {
        public long DOCUMENT_CATEGORY_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string DOCUMENT_PATH { get; set; }
        public Nullable<long> DOCUMENTS_CATEGORY_MAIN_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public string Practice_Code { get; set; }
        public bool ISSHAREDGLOBALLY { get; set; }
        public string DOCUMENT_COLOR { get; set; }
    }
}
