//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFS_Suggested
    {
        public int Practice_code { get; set; }
        public string CPT { get; set; }
        public string Modi_code1 { get; set; }
        public long insPayer_id { get; set; }
        public Nullable<decimal> amount_approved { get; set; }
        public Nullable<int> Suggested { get; set; }
    }
}
