//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFS_ImpactSummary
    {
        public long practice_code { get; set; }
        public Nullable<decimal> Current_Billed { get; set; }
        public Nullable<decimal> Current_Approved { get; set; }
        public Nullable<decimal> current_paid { get; set; }
        public Nullable<int> EFS_Billed { get; set; }
        public Nullable<decimal> EFS_Approved { get; set; }
        public Nullable<decimal> EFS_Adjusted { get; set; }
        public Nullable<decimal> Current_Adjusted { get; set; }
        public Nullable<decimal> CurrentAC_Ratio { get; set; }
        public Nullable<decimal> EFS_AC_Ratio { get; set; }
        public Nullable<decimal> CurrentPC_Ratio { get; set; }
        public Nullable<decimal> EFS_PC_Ratio { get; set; }
        public Nullable<int> Current_BillEqApp { get; set; }
        public Nullable<int> EFS_BillEqApp { get; set; }
        public Nullable<double> CurrentBeqApp_Ratio { get; set; }
        public Nullable<double> EFS_BeqApp_Ratio { get; set; }
        public Nullable<int> sum_nonP_billeqapp_Current { get; set; }
        public Nullable<int> sum_nonP_billeqapp_EFS { get; set; }
    }
}
