//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInformation
    {
        public long Employee_Id { get; set; }
        public string Nic_Number { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public string Father_Husband_Info { get; set; }
        public string Father_Husband_First_Name { get; set; }
        public string Father_Husband_Middle_initial { get; set; }
        public string Father_Husband_Last_Name { get; set; }
        public string Permanent_Address { get; set; }
        public string Permanent_City { get; set; }
        public string Permanent_State { get; set; }
        public string Permanent_Postal_Code { get; set; }
        public string Personal_Contact_Number { get; set; }
        public string Home_Contact_Number { get; set; }
        public string Emergency_Contact_Number { get; set; }
        public string Email_Personal { get; set; }
        public string Email_Office { get; set; }
        public Nullable<System.DateTime> Joining_Date { get; set; }
        public Nullable<long> DesignationId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public string Salary_Type { get; set; }
        public string Current_Salary { get; set; }
        public string Bank_Account_Number { get; set; }
        public string Family_Code { get; set; }
        public string IsEOBI { get; set; }
        public string EOBI_No { get; set; }
        public string IsNTN { get; set; }
        public string NTN_No { get; set; }
        public string Passport_Number { get; set; }
        public string Team_Leader { get; set; }
        public string Supervisor_Manager { get; set; }
        public Nullable<System.DateTime> Resignation_Date { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<System.DateTime> Rejoining_date { get; set; }
        public string Emergency_contact_person { get; set; }
        public string change { get; set; }
        public string SP_Last_Name { get; set; }
        public string SP_First_Name { get; set; }
        public string SP_Middle_Initial { get; set; }
        public string SP_Gender { get; set; }
        public string SP_Relation { get; set; }
        public Nullable<System.DateTime> SP_Date_Of_Birth { get; set; }
        public string SP_Nic_Number { get; set; }
        public string Is_Employee { get; set; }
        public Nullable<long> SP_Employee_Id { get; set; }
        public string Zone_Code { get; set; }
        public string NIC_verified { get; set; }
        public string Eye_Color { get; set; }
        public string Height { get; set; }
        public string Blood_Group { get; set; }
        public string Licence_Number { get; set; }
        public Nullable<bool> Probation_Completed { get; set; }
        public Nullable<bool> Internee { get; set; }
        public string Title_Of_Acc { get; set; }
        public string Personal_Contact_Number_encrypt { get; set; }
        public string Home_Contact_Number_encrypt { get; set; }
        public string Emergency_Contact_Number_encrypt { get; set; }
        public Nullable<bool> Hold_Salary { get; set; }
        public Nullable<System.DateTime> License_Expiry_Date { get; set; }
        public Nullable<System.DateTime> NIC_Expiry_Date { get; set; }
        public Nullable<System.DateTime> Passport_Expiry_Date { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<System.DateTime> Shift_EffectiveDate { get; set; }
        public Nullable<bool> SocailSecurity { get; set; }
        public string Emp_Status { get; set; }
        public string DayTime_Contact { get; set; }
        public string Evening_Contact { get; set; }
        public string Emp_Position { get; set; }
        public Nullable<long> Emp_Direct_Manager { get; set; }
        public string Religion { get; set; }
        public Nullable<long> TeamId { get; set; }
        public Nullable<long> UserId { get; set; }
    }
}
