//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENROLLMENT_TRACKER
    {
        public string practice_code { get; set; }
        public string which_page { get; set; }
        public string status { get; set; }
        public string page_stat { get; set; }
        public string stat_pageName { get; set; }
    }
}
