//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class era
    {
        public long era_id { get; set; }
        public string transaction_handling_code { get; set; }
        public Nullable<decimal> check_amount { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public string check_number { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public string payer_identifier_qualifier { get; set; }
        public string payer_identifier { get; set; }
        public string payer_contact_information { get; set; }
        public string payer_name { get; set; }
        public string payer_address { get; set; }
        public string payer_state { get; set; }
        public string payer_city { get; set; }
        public string payer_zip { get; set; }
        public string payee_name { get; set; }
        public string payee_identifier_code_qualifier { get; set; }
        public string payee_identifier_code { get; set; }
        public string payee_address { get; set; }
        public string payee_city { get; set; }
        public string payee_state { get; set; }
        public string payee_zip { get; set; }
        public string additional_payee_identifier_code_qualifier { get; set; }
        public string additional_payee_identifier_code { get; set; }
        public string provider_summary { get; set; }
        public string provider_supplemental_summary { get; set; }
        public string file_name { get; set; }
        public Nullable<bool> is_error { get; set; }
        public string error_detail { get; set; }
        public string created_user { get; set; }
        public Nullable<long> practice_id { get; set; }
        public Nullable<long> provider_id { get; set; }
        public Nullable<System.DateTime> client_date_created { get; set; }
        public string modified_user { get; set; }
        public Nullable<System.DateTime> client_date_modified { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string system_ip { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string payer_business_contact_information { get; set; }
        public string payer_technical_contact_information { get; set; }
        public string payer_website { get; set; }
        public string file_path { get; set; }
        public Nullable<bool> posted { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
        public Nullable<bool> is_processed { get; set; }
        public string new_file_path { get; set; }
        public string old_file_path { get; set; }
        public string payment_method_code { get; set; }
        public Nullable<long> payer_id { get; set; }
    }
}
