//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA_ADJUSTMENT_MAPPING_BKP_012721
    {
        public long S_No { get; set; }
        public string Adjustment_Code { get; set; }
        public string Description { get; set; }
        public string Code_Type { get; set; }
        public string Category_Code { get; set; }
        public string Map_Code { get; set; }
        public Nullable<long> EOB_S_NO { get; set; }
        public Nullable<bool> Active_Status { get; set; }
        public Nullable<System.DateTime> Start_Effective_Date { get; set; }
        public Nullable<System.DateTime> End_Effective_Date { get; set; }
        public string Created_BY { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string RESPONSIBLE_DEPT { get; set; }
        public string INSURANCE_TYPE { get; set; }
        public string INS_PAYERS { get; set; }
    }
}
