//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class era_claim
    {
        public long era_claim_id { get; set; }
        public Nullable<long> era_id { get; set; }
        public Nullable<long> claim_id { get; set; }
        public Nullable<long> patient_id { get; set; }
        public Nullable<decimal> claim_billed_amount { get; set; }
        public Nullable<decimal> claim_paid_amount { get; set; }
        public Nullable<decimal> patient_responsibility { get; set; }
        public string claim_filing_indicator_code { get; set; }
        public string payer_claim_control_number { get; set; }
        public Nullable<decimal> claim_adj_amount { get; set; }
        public string claim_adj_codes { get; set; }
        public string claim_remark_codes { get; set; }
        public string patient_fname { get; set; }
        public string patient_lname { get; set; }
        public string patient_mname { get; set; }
        public string patient_identifier_qualfier { get; set; }
        public string patient_identifier { get; set; }
        public string subscriber_entity_type { get; set; }
        public string subscriber_identifier_qualfier { get; set; }
        public string subscriber_identifier { get; set; }
        public string subscriber_fname { get; set; }
        public string subscriber_lname { get; set; }
        public string subscriber_mname { get; set; }
        public string rendering_provider_lname { get; set; }
        public string rendering_provider_fname { get; set; }
        public string rendering_provider_identifier_qualifier { get; set; }
        public string rendering_provider_identifier { get; set; }
        public Nullable<System.DateTime> claim_statement_period_start { get; set; }
        public Nullable<System.DateTime> claim_statemnent_period_end { get; set; }
        public Nullable<decimal> coverage_amount { get; set; }
        public Nullable<decimal> claim_interest { get; set; }
        public string non_convered_estimated_NE { get; set; }
        public string claim_status_code { get; set; }
        public string claim_supplemental_information_quantity_qualifier { get; set; }
        public string claim_supplemental_information_quantity { get; set; }
        public string patient_responsibility_reason_code { get; set; }
        public Nullable<long> practice_id { get; set; }
        public string mapped_by { get; set; }
        public Nullable<System.DateTime> date_mapped { get; set; }
        public Nullable<bool> posted { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> client_date_created { get; set; }
        public string modified_user { get; set; }
        public Nullable<System.DateTime> client_date_modified { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string system_ip { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string corrected_insured_entity_type { get; set; }
        public string corrected_insured_lname { get; set; }
        public string corrected_insured_fname { get; set; }
        public string corrected_insured_mname { get; set; }
        public string corrected_insured_identifier_qualifier { get; set; }
        public string corrected_insured_identifier { get; set; }
        public Nullable<long> mapped_insurance_id { get; set; }
        public string crossover_carrier_name { get; set; }
    }
}
