//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class era_adjustment
    {
        public long era_adjustment_id { get; set; }
        public string adjustment_group_code { get; set; }
        public string adjustment_reason_code { get; set; }
        public Nullable<decimal> adjustment_amount { get; set; }
        public Nullable<long> era_id { get; set; }
        public Nullable<long> era_claim_id { get; set; }
        public Nullable<long> era_claim_service_id { get; set; }
        public Nullable<long> claim_procedures_id { get; set; }
        public Nullable<long> claim_id { get; set; }
        public Nullable<long> practice_id { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> client_date_created { get; set; }
        public string modified_user { get; set; }
        public Nullable<System.DateTime> client_date_modified { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string system_ip { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
