//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class era_provider_adjustment
    {
        public long provider_adjustment_id { get; set; }
        public Nullable<long> era_id { get; set; }
        public string reason_code { get; set; }
        public string adjustment_identifier { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string provider_identifier { get; set; }
        public Nullable<System.DateTime> fiscal_year_end_date { get; set; }
        public Nullable<long> practice_id { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
