//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class era_claim_service
    {
        public long era_claim_service_id { get; set; }
        public Nullable<long> era_id { get; set; }
        public Nullable<long> era_claim_id { get; set; }
        public Nullable<long> practice_id { get; set; }
        public Nullable<System.DateTime> begin_service_date { get; set; }
        public Nullable<System.DateTime> end_service_date { get; set; }
        public string paid_units { get; set; }
        public Nullable<decimal> allowed_amount { get; set; }
        public Nullable<decimal> deduct_amount { get; set; }
        public Nullable<decimal> coIns_amount { get; set; }
        public Nullable<decimal> coPay_amount { get; set; }
        public Nullable<decimal> late_filing_reduction { get; set; }
        public Nullable<decimal> other_adjusts { get; set; }
        public string adjust_codes { get; set; }
        public string remark_codes { get; set; }
        public string provider_control_number { get; set; }
        public Nullable<decimal> billed_amount { get; set; }
        public Nullable<decimal> paid_amount { get; set; }
        public Nullable<decimal> patient_responsibility { get; set; }
        public string correction_reversals { get; set; }
        public Nullable<decimal> risk_amount { get; set; }
        public string per_day_limit { get; set; }
        public Nullable<decimal> net_billed { get; set; }
        public Nullable<decimal> tax { get; set; }
        public string rendering_provider_identifier_qualifier { get; set; }
        public string rendering_provider_identifier { get; set; }
        public string charged_procedure { get; set; }
        public string charged_procedure_modifier { get; set; }
        public string paid_procedure { get; set; }
        public string paid_procedure_modifier { get; set; }
        public Nullable<long> claim_procedures_id { get; set; }
        public Nullable<decimal> posted_amount { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> client_date_created { get; set; }
        public string modified_user { get; set; }
        public Nullable<System.DateTime> client_date_modified { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string system_ip { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> payment_posted { get; set; }
        public Nullable<bool> auto_posted { get; set; }
        public Nullable<bool> denial_posted { get; set; }
        public Nullable<System.DateTime> date_mapped { get; set; }
        public string mapped_by { get; set; }
    }
}
