//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERACHECKDETAIL
    {
        public int ERAID { get; set; }
        public string PAYERNAME { get; set; }
        public string PAYERADDRESS { get; set; }
        public string PAYERCITY { get; set; }
        public string PAYERSTATE { get; set; }
        public string PAYERZIP { get; set; }
        public string PROVIDERNAME { get; set; }
        public string PROVIDERADDRESS { get; set; }
        public string PROVIDERCITY { get; set; }
        public string PROVIDERSTATE { get; set; }
        public string PROVIDERZIP { get; set; }
        public string PROVIDERTAXID { get; set; }
        public string CHECKNUMBER { get; set; }
        public Nullable<System.DateTime> CHECKDATE { get; set; }
        public string CHECKAMOUNT { get; set; }
        public Nullable<bool> is_duplicate { get; set; }
    }
}
