//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ethnicity
    {
        public long ethnicity_id { get; set; }
        public string ethnicity_code { get; set; }
        public string ethnicity_description { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
