//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility_Insurance_Id
    {
        public long Facility_Code { get; set; }
        public Nullable<long> InsPayer_Id { get; set; }
        public string FACILITY_ID { get; set; }
    }
}
