//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiancial_Summary
    {
        public long PRACTICE_CODE { get; set; }
        public string PRAC_NAME { get; set; }
        public Nullable<long> ATTENDING_PHYSICIAN { get; set; }
        public Nullable<long> BILLING_PHYSICIAN { get; set; }
        public long CLAIM_NO { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public Nullable<decimal> Amt_Due { get; set; }
        public string PROCEDURE_CODE { get; set; }
        public Nullable<System.DateTime> Date_Entry { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> AMOUNT_PAID { get; set; }
        public Nullable<decimal> CONTRACTUL_ADJUSTMENT { get; set; }
        public Nullable<int> BILLID_UNIT { get; set; }
        public int CHARGE_IN_AR { get; set; }
        public Nullable<long> INSURANCE_ID { get; set; }
        public Nullable<long> INSPAYER_ID { get; set; }
        public string INSPAYER_DESCRIPTION { get; set; }
    }
}
