//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCIAL_SUMMARY_REPORT
    {
        public string PROCEDURE_CODE { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<long> PRACTICE_CODE { get; set; }
        public string RENDERRING_PROVIDER { get; set; }
        public Nullable<int> BILLED_UNITS { get; set; }
        public decimal BILLED_CHARGE { get; set; }
        public decimal INSURANCE_CHARGE { get; set; }
        public decimal SELF_CHARGE { get; set; }
        public decimal AMTDUE { get; set; }
        public decimal PAYMENTS { get; set; }
        public decimal INSURANCE_PAYMENTS { get; set; }
        public decimal PATIENT_PAYMENTS { get; set; }
        public decimal CONTRACTUAL_ADJUSTMENTS { get; set; }
        public decimal WRITEOFF_ADJUSTMENTS { get; set; }
        public Nullable<int> PATIENT_COUNT { get; set; }
    }
}
