//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowSheet_Items
    {
        public long FlowSheet_Item_Id { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string Created_by { get; set; }
        public string Created_date { get; set; }
        public string Modified_by { get; set; }
        public string Modified_date { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string Gender { get; set; }
        public Nullable<long> Practice_code { get; set; }
    }
}
