//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Get_CustomEdits_Colums
    {
        public int Id { get; set; }
        public string Column_Name { get; set; }
        public string Table_Name { get; set; }
        public string Status { get; set; }
    }
}
