//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guarantor
    {
        public long Guarantor_Code { get; set; }
        public string Guarant_Lname { get; set; }
        public string Guarant_Fname { get; set; }
        public string Guarant_Mi { get; set; }
        public string Guarant_Address { get; set; }
        public string Guarant_City { get; set; }
        public string Guarant_State { get; set; }
        public string Guarant_Zip { get; set; }
        public Nullable<System.DateTime> Guarant_Dob { get; set; }
        public string Guarant_Ssn { get; set; }
        public string Guarant_Gender { get; set; }
        public string Guarant_Home_Phone { get; set; }
        public string GUARANT_Work_Phone { get; set; }
        public string GUARANT_Work_Phone_Ext { get; set; }
        public Nullable<bool> Exported { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTimeOffset> created_date { get; set; }
        public Nullable<long> modified_by { get; set; }
        public Nullable<System.DateTimeOffset> modified_date { get; set; }
        public string Guarant_Type { get; set; }
    }
}
