//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCFAImage
    {
        public long HCFA_Image_Id { get; set; }
        public Nullable<long> Claim_No { get; set; }
        public string Image_Name { get; set; }
        public string Pri_Sec_Oth_Type { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Submission_Via { get; set; }
        public Nullable<long> Att_Type_Id { get; set; }
        public Nullable<int> Seq_No { get; set; }
        public string Appeal_ID { get; set; }
    }
}
