//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcpc_code_lookup
    {
        public string hcpc_code_id { get; set; }
        public int hcpc_code_version { get; set; }
        public string long_description { get; set; }
        public string short_description { get; set; }
        public System.DateTime last_updated { get; set; }
    }
}
