//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIPAA_278_PAYER_INFORMATION
    {
        public long S_NO { get; set; }
        public string Payer_ID { get; set; }
        public string Payer_Name { get; set; }
        public string Payer_Source { get; set; }
        public Nullable<bool> Request_for_Referral { get; set; }
        public Nullable<bool> Prior_Authorization { get; set; }
        public Nullable<bool> Admission_Review { get; set; }
        public Nullable<bool> IS_RealTime { get; set; }
        public string Access_Level { get; set; }
        public Nullable<bool> Web_Access { get; set; }
        public Nullable<bool> EMR_Access { get; set; }
        public Nullable<bool> Soft_Access { get; set; }
        public Nullable<bool> Payer_Active { get; set; }
        public Nullable<bool> IS_Future { get; set; }
        public string Future_Dates_Range { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_by { get; set; }
        public Nullable<long> Practice_code { get; set; }
    }
}
