//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospital_affilation
    {
        public string user_name { get; set; }
        public int rowid { get; set; }
        public string hos_name { get; set; }
        public string hos_city { get; set; }
        public string hos_state { get; set; }
        public string hos_zip { get; set; }
        public string hos_phone { get; set; }
    }
}
