//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class include_in_edi
    {
        public Nullable<long> claim_charges_id { get; set; }
        public long Claim_No { get; set; }
        public int Sequence_No { get; set; }
        public string Procedure_Code { get; set; }
        public Nullable<System.DateTime> DOE { get; set; }
        public System.DateTime Dos_From { get; set; }
        public Nullable<System.DateTime> Dos_To { get; set; }
        public string POS { get; set; }
        public string DX_Pointer1 { get; set; }
        public string DX_Pointer2 { get; set; }
        public string DX_Pointer3 { get; set; }
        public string DX_Pointer4 { get; set; }
        public string Modi_Code1 { get; set; }
        public string Modi_Code2 { get; set; }
        public string Modi_Code3 { get; set; }
        public string Modi_Code4 { get; set; }
        public Nullable<int> Units { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> Include_In_Edi1 { get; set; }
        public Nullable<bool> Include_In_Sdf { get; set; }
        public string Unit_Time_Day { get; set; }
        public Nullable<bool> PTL_Status { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<System.DateTime> Sync_Date { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> Stop_Time { get; set; }
        public Nullable<System.DateTime> EMR_DOE { get; set; }
        public string Drug_Code { get; set; }
        public System.Guid rowguid34 { get; set; }
    }
}
