//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class instruction_history_New
    {
        public long id { get; set; }
        public Nullable<long> question_id { get; set; }
        public string instruction { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modify_by { get; set; }
        public Nullable<long> practice_code { get; set; }
        public string Reference_Instruction_ID { get; set; }
    }
}
