//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public long Insurance_Id { get; set; }
        public Nullable<long> InsPayer_Id { get; set; }
        public string Insurance_Address { get; set; }
        public string Insurance_City { get; set; }
        public string Insurance_State { get; set; }
        public string Insurance_Zip { get; set; }
        public string Insurance_CardCategory { get; set; }
        public string Insurance_Phone_Type1 { get; set; }
        public string Insurance_Phone_Type2 { get; set; }
        public string Insurance_Phone_Type3 { get; set; }
        public string Insurance_Phone_Number1 { get; set; }
        public string Insurance_Phone_Number2 { get; set; }
        public string Insurance_Phone_Number3 { get; set; }
        public Nullable<int> Insurance_Department { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public Nullable<bool> Is_Sec_Attach_Need { get; set; }
        public Nullable<bool> IS_SEC_Paper { get; set; }
        public Nullable<bool> InActive { get; set; }
        public string EPSDT_WorkerInfo { get; set; }
        public string Sub_Method { get; set; }
        public Nullable<System.DateTime> Time_From { get; set; }
        public Nullable<System.DateTime> Time_To { get; set; }
        public string STOP_SUBMISSION { get; set; }
        public string ClaimFilingLimit { get; set; }
        public string AppealFilingLimit { get; set; }
    }
}
