//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance_Denials
    {
        public long Insurance_Denial_Code { get; set; }
        public string Denial_Code { get; set; }
        public string Discription { get; set; }
        public string Reason { get; set; }
        public string Corrective_Action { get; set; }
        public string Referance_Claims { get; set; }
        public string Insurance { get; set; }
        public string State { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<System.DateTime> Denial_Date { get; set; }
        public string Explanation { get; set; }
        public string Suggested_action { get; set; }
        public string Enter_Form { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
