//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSURANCE_PAYERS_PLAN
    {
        public long S_NO { get; set; }
        public Nullable<long> PRACTICE_CODE { get; set; }
        public Nullable<long> INSPAYER_ID { get; set; }
        public Nullable<double> RATE { get; set; }
        public string TYPE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODFIED_DATE { get; set; }
        public string MODFIED_BY { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> INVOICE_PLAN_ID { get; set; }
    }
}
