//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance_Phone_Directory
    {
        public long Phone_Directory_Id { get; set; }
        public Nullable<long> Insurance_Id { get; set; }
        public string Insurance_Name { get; set; }
        public string State { get; set; }
        public string Phone_No { get; set; }
        public string Extension { get; set; }
        public string Phone_Type { get; set; }
        public string contact_Person { get; set; }
        public string Department { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
