//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance_payers_formats
    {
        public long Sr_No { get; set; }
        public string Rule_Type { get; set; }
        public Nullable<long> InsPayer_Id { get; set; }
        public string Provider_No_Length { get; set; }
        public string Pro_Prefix_Length { get; set; }
        public Nullable<bool> Pro_No_Fix { get; set; }
        public string Pro_Prefix_Type { get; set; }
        public string Pro_No_Min_Length { get; set; }
        public string Pro_No_Max_Length { get; set; }
        public string pro_Suffix_Length { get; set; }
        public string Pro_Suffix_Type { get; set; }
        public string Group_No_Length { get; set; }
        public Nullable<bool> Group_Length_Fix { get; set; }
        public string Group_No_Min_Length { get; set; }
        public string Group_No_Max_Length { get; set; }
        public string Group_Prefix_Length { get; set; }
        public string Group_prefix_Type { get; set; }
        public string Group_Suffix_Length { get; set; }
        public string Group_Suffix_Type { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
