//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurancelist
    {
        public string Insgroup_Name { get; set; }
        public long inspayer_id { get; set; }
        public string inspayer_description { get; set; }
        public string inspayer_837_id { get; set; }
        public string inspayer_state { get; set; }
        public long insurance_id { get; set; }
        public string insurance_address { get; set; }
        public string insurance_state { get; set; }
        public string insurance_type_code { get; set; }
    }
}
