//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSURANCE_FILING_LIMIT
    {
        public long INSURANCE_FILING_LIMIT_ID { get; set; }
        public long Payer_ID { get; set; }
        public string TIME_TYPE { get; set; }
        public string FROMMONTH { get; set; }
        public string TOMONTH { get; set; }
        public string PRI_SEC_OTH_TYPE { get; set; }
        public Nullable<int> FILING_APPEAL_LIMIT { get; set; }
        public Nullable<int> APPEAL_LIMIT { get; set; }
        public string APPEAL_DATE_TYPE { get; set; }
        public string Appeal_Level { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREADTED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string ENROLLMENT_TYPE { get; set; }
        public string NETWORK_TYPE { get; set; }
    }
}
