//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lcd
    {
        public int lcd_id { get; set; }
        public int lcd_version { get; set; }
        public string title { get; set; }
        public string determination_number { get; set; }
        public Nullable<System.DateTime> orig_det_eff_date { get; set; }
        public string orig_det_eff_dt_type { get; set; }
        public Nullable<System.DateTime> ent_det_end_date { get; set; }
        public Nullable<System.DateTime> rev_eff_date { get; set; }
        public string rev_eff_dt_type { get; set; }
        public Nullable<System.DateTime> rev_end_date { get; set; }
        public string indication { get; set; }
        public string diagnoses_support { get; set; }
        public string icd9_dont_support_para { get; set; }
        public string icd9_dont_support_ast { get; set; }
        public string diagnoses_dont_support { get; set; }
        public string coding_guidelines { get; set; }
        public string doc_reqs { get; set; }
        public string appendices { get; set; }
        public string util_guide { get; set; }
        public string source_info { get; set; }
        public string adv_meeting { get; set; }
        public Nullable<System.DateTime> comment_start_dt { get; set; }
        public Nullable<System.DateTime> comment_end_dt { get; set; }
        public Nullable<System.DateTime> notice_start_dt { get; set; }
        public string rev_hist_num { get; set; }
        public string history_exp { get; set; }
        public Nullable<System.DateTime> last_reviewed_on { get; set; }
        public string status { get; set; }
        public System.DateTime last_updated { get; set; }
        public string cms_cov_policy { get; set; }
        public Nullable<int> display_id { get; set; }
        public Nullable<int> draft_contact { get; set; }
    }
}
