//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lcd_related_documents
    {
        public int lcd_id { get; set; }
        public int lcd_version { get; set; }
        public int related_num { get; set; }
        public Nullable<int> r_lmrp_id { get; set; }
        public Nullable<int> r_lmrp_version { get; set; }
        public Nullable<int> r_article_id { get; set; }
        public Nullable<int> r_article_version { get; set; }
        public Nullable<int> r_lcd_id { get; set; }
        public Nullable<int> r_lcd_version { get; set; }
    }
}
