//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkup_location_ids
    {
        public string LOCATION_ID { get; set; }
        public string LOCATION_SERVER_IP { get; set; }
        public string LOCATION_SERVER_NAME { get; set; }
        public string LOCATION_CHAR_CODE { get; set; }
        public Nullable<short> LOCATION_NUM_CODE { get; set; }
        public string LOCATION_SERIAL_CODE { get; set; }
        public string LOCATION_TEMP_CODE { get; set; }
    }
}
