//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mainfacility
    {
        public int FACILITY_CODE { get; set; }
        public string FACILITY_NAME { get; set; }
        public string FACILITY_ADDRESS { get; set; }
        public string FACILITY_CITY { get; set; }
        public string FACILITY_STATE { get; set; }
        public string FACILITY_ZIP { get; set; }
        public string FACILITY_CONTACT_NAME { get; set; }
        public string FACILITY_ID_NUMBER { get; set; }
        public string FACILITY_PHONE { get; set; }
        public string FACILITY_TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public string exported { get; set; }
        public string practicecode { get; set; }
        public Nullable<long> hl7_facility_code { get; set; }
        public string NPI { get; set; }
        public System.Guid rowguid20 { get; set; }
    }
}
