//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medigap_Insurances
    {
        public long InsPayer_Id { get; set; }
        public string Medigap_Carrier_Code { get; set; }
        public string Carrier_Name { get; set; }
        public long Insurance_Id { get; set; }
    }
}
