//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICINE
    {
        public long MEDICINE_CODE { get; set; }
        public Nullable<long> Med_Generic_Name_ID { get; set; }
        public string MEDICINE_TRADE { get; set; }
        public Nullable<bool> RX { get; set; }
        public Nullable<bool> OCT { get; set; }
        public string MEDICINE_NOTES { get; set; }
        public string MEDICINE_DOSAGE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<bool> RECENT { get; set; }
        public Nullable<bool> IS_DEMO { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string NDC_Code { get; set; }
        public string Generic_Description { get; set; }
        public Nullable<long> Generic_med_code { get; set; }
        public string OTC { get; set; }
        public string Generic { get; set; }
        public string RxNorm { get; set; }
        public long practice_code { get; set; }
        public string Quantity_Qualifier_Description { get; set; }
        public string Quantity_Qualifier_Code { get; set; }
        public Nullable<int> IS_CONTROLLEDDRUG { get; set; }
    }
}
