//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICINE_FORMULATION
    {
        public long MEDICINE_FORMULATION_CODE { get; set; }
        public Nullable<long> MEDICINE_CODE { get; set; }
        public string UNIT_CODE { get; set; }
        public Nullable<long> DOSAGE_CODE { get; set; }
        public string STRENGTH { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<bool> DELETED { get; set; }
    }
}
