//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMO_MAPPING_PRACTICE_PLAN
    {
        public int SR_NO { get; set; }
        public Nullable<int> MEMO_CODE { get; set; }
        public Nullable<int> PRACTICE_CODE { get; set; }
        public string MEMO_TYPE { get; set; }
        public string Prac_emr_name { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public string MEMO_POINTER { get; set; }
    }
}
