//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMO_MAPPING
    {
        public double MEMO_ID { get; set; }
        public string MEMO_NAME { get; set; }
        public string MEMO_DESCRIPTION { get; set; }
        public Nullable<double> MEMO_MAPPING_CODE { get; set; }
        public Nullable<double> OLD_CODE { get; set; }
        public string MEMO_PLAN_BASIS { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<double> MEMO_PRIORITY { get; set; }
    }
}
