//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_TBL_CPT_Reason
    {
        public long CPT_Reason_ID { get; set; }
        public Nullable<long> Claim_payment_Id { get; set; }
        public Nullable<long> Claim_No { get; set; }
        public string CPT_Reason { get; set; }
        public string Case_No { get; set; }
        public string CPT_Code { get; set; }
        public Nullable<bool> Invalid_Reason { get; set; }
        public string Created_BY { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> FEEDBACK_DATE { get; set; }
        public string FilePath { get; set; }
    }
}
