//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_TBL_Insurance_Resources_Remarks
    {
        public long Remarks_Id { get; set; }
        public long Claim_No { get; set; }
        public string URL1_Remark { get; set; }
        public string URL2_Remark { get; set; }
        public string URL3_Remark { get; set; }
        public string Report_Remark { get; set; }
        public string IVR_Remark { get; set; }
        public string Fax_Remark { get; set; }
        public string FaxRemark_Remark { get; set; }
        public string FaxPath_Remark { get; set; }
        public string Duration_Remark { get; set; }
        public string GenInfo_Remark { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public long InsPayer_Id { get; set; }
    }
}
