//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAME
    {
        public long INSNAME_ID { get; set; }
        public string INSNAME_DESCRIPTION { get; set; }
        public Nullable<int> DAYS { get; set; }
        public Nullable<int> CNT { get; set; }
    }
}
