//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDC_CrossWalk
    {
        public long NDC_ID { get; set; }
        public string HCPCS_Code { get; set; }
        public string Labeler_Name { get; set; }
        public string NDC2 { get; set; }
        public string Drug_Name { get; set; }
        public string HCPCS_Dosage { get; set; }
        public string PKG_Size { get; set; }
        public string PKG_Qty { get; set; }
        public string ILL_UNITS { get; set; }
        public string NITS_PKG { get; set; }
        public string Short_Description { get; set; }
        public Nullable<System.DateTime> Effective_Date_From { get; set; }
        public Nullable<System.DateTime> Effective_Date_To { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Qualifier { get; set; }
        public Nullable<long> Practice_Code { get; set; }
    }
}
