//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEW_PATIENTLETTER_FIELDS
    {
        public long FIELD_ID { get; set; }
        public string FIELD_TEXT { get; set; }
        public string FIELD_QRY { get; set; }
        public string FIELD_CATAGORY { get; set; }
        public Nullable<bool> FIELD_SHOW { get; set; }
    }
}
