//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEW_GCODE
    {
        public long GCODE { get; set; }
        public Nullable<bool> PAT_DELETED { get; set; }
        public long PATIENT_ACCOUNT { get; set; }
        public Nullable<long> PRACTICE_CODE { get; set; }
        public long GUARANTOR_CODE { get; set; }
        public string GUARANT_LNAME { get; set; }
        public string GUARANT_FNAME { get; set; }
        public string GUARANT_MI { get; set; }
        public string GUARANT_ADDRESS { get; set; }
        public string GUARANT_CITY { get; set; }
        public string GUARANT_STATE { get; set; }
        public string GUARANT_ZIP { get; set; }
        public Nullable<System.DateTime> GUARANT_DOB { get; set; }
        public string GUARANT_SSN { get; set; }
        public string GUARANT_GENDER { get; set; }
        public string GUARANT_HOME_PHONE { get; set; }
        public string GUARANT_WORK_PHONE { get; set; }
        public string GUARANT_WORK_PHONE_EXT { get; set; }
        public Nullable<long> MTBCGUARANTOR_CODE { get; set; }
        public Nullable<bool> EXPORTED { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<bool> IS_DEMO { get; set; }
        public Nullable<long> GUARANT_EMPLOYER_CODE { get; set; }
        public System.DateTime Sync_Date { get; set; }
        public Nullable<long> guarant_practice_code { get; set; }
        public string Guarant_Type { get; set; }
        public Nullable<int> NO_OFPATIENT { get; set; }
    }
}
