//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes_Description
    {
        public long Note_Id { get; set; }
        public string Note_Description { get; set; }
        public string Note_Type { get; set; }
        public string Reminder_Type { get; set; }
        public Nullable<int> No_Of_Days { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<long> MTBC_Soft_Code { get; set; }
        public string patient_claim { get; set; }
        public Nullable<bool> ATTACHMENT { get; set; }
        public Nullable<bool> note_disabled { get; set; }
        public Nullable<long> Notes_category_id { get; set; }
    }
}
