//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class office_employees
    {
        public string user_name { get; set; }
        public int row_id { get; set; }
        public string name { get; set; }
        public string responsibility { get; set; }
        public string daily_work { get; set; }
    }
}
