//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public int OfficeId { get; set; }
        public int CompanyId { get; set; }
        public string OfficeName { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<bool> DELETED { get; set; }
    }
}
