//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Notes
    {
        public long Patient_Notes_Id { get; set; }
        public Nullable<long> Patient_Account { get; set; }
        public Nullable<long> Ptn_Note_Id { get; set; }
        public string Ptn_Scan_No { get; set; }
        public string Ptn_Note_Content { get; set; }
        public Nullable<long> Ptn_Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Ptn_Created_Date { get; set; }
        public Nullable<long> Ptn_Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Ptn_Modified_Date { get; set; }
        public Nullable<bool> Ptn_Deleted { get; set; }
        public Nullable<System.DateTime> Scan_Date { get; set; }
        public Nullable<int> Page_no { get; set; }
        public string Created_From { get; set; }
        public string Modified_from { get; set; }
    }
}
