//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Ptl_Feedback
    {
        public long Patient_Account { get; set; }
        public string Reasons { get; set; }
        public string User_Notes { get; set; }
        public System.DateTimeOffset Notes_Date { get; set; }
        public string FeedBack { get; set; }
        public Nullable<System.DateTimeOffset> FeedBack_Date { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
    }
}
