//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_bkp11282018
    {
        public Nullable<System.DateTime> DeathDate { get; set; }
        public long Patient_Account { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string MI { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Marital_Status { get; set; }
        public Nullable<int> Address_Type { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string Home_Phone { get; set; }
        public string Business_Phone { get; set; }
        public Nullable<long> Financial_Guarantor { get; set; }
        public Nullable<int> Gurantor_Relation { get; set; }
        public string Email_Address { get; set; }
        public string Eligibility_Status { get; set; }
        public Nullable<long> Location_Code { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Chart_Id { get; set; }
        public Nullable<bool> Move_Collection { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public Nullable<bool> Patient_Payment_Plan { get; set; }
        public Nullable<bool> Patient_Statement { get; set; }
        public string Patient_Type { get; set; }
        public string Scan_No { get; set; }
        public Nullable<bool> @as { get; set; }
        public string PTL_Web_Appearnce_Days { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> PTL_STATUS { get; set; }
        public Nullable<System.DateTime> PTL_Date { get; set; }
        public Nullable<System.DateTime> Scan_Date { get; set; }
        public Nullable<long> Provider_Code { get; set; }
        public Nullable<long> alternate_id { get; set; }
        public string Notes { get; set; }
        public string Cell_Phone { get; set; }
        public string Ext { get; set; }
        public Nullable<long> Referring_Physician { get; set; }
        public Nullable<bool> Address_To_Guarantor { get; set; }
        public string Special_Billing_Note { get; set; }
        public Nullable<long> CREATED_FROM { get; set; }
        public string ALTERNATE_PHONE { get; set; }
        public Nullable<bool> Terminated { get; set; }
        public string Primary_Phone { get; set; }
        public Nullable<int> Ethnicities { get; set; }
        public Nullable<int> Race { get; set; }
        public Nullable<int> Languages { get; set; }
        public Nullable<bool> IsDeceased { get; set; }
        public string DeathCause { get; set; }
        public Nullable<bool> Chk_Hospice { get; set; }
        public string Father_Cell { get; set; }
        public string Father_FName { get; set; }
        public string Father_LName { get; set; }
        public string Mother_Cell { get; set; }
        public string Mother_FName { get; set; }
        public string Mother_LName { get; set; }
        public string Spouse_Cell { get; set; }
        public string Spouse_Fname { get; set; }
        public string Spouse_Lname { get; set; }
        public Nullable<System.DateTime> Registration_Complete_Date { get; set; }
        public Nullable<bool> Prac_Address_PT_Billing { get; set; }
        public string RACE2 { get; set; }
        public string Address_Line2 { get; set; }
        public string Blood_Type { get; set; }
        public Nullable<long> Primary_Care_Physician { get; set; }
        public Nullable<bool> Is_Self_Pay { get; set; }
        public string Patient_Category { get; set; }
        public string Adjuster_Name { get; set; }
        public string Adjuster_Phone { get; set; }
        public Nullable<System.DateTime> Inactivation_Date { get; set; }
        public Nullable<long> Family_Id { get; set; }
        public string Fam_Relation { get; set; }
        public Nullable<bool> FamilyBit { get; set; }
        public Nullable<bool> GuarantorBit { get; set; }
        public string Family_Name { get; set; }
        public Nullable<bool> Address_To_Family { get; set; }
        public Nullable<int> ChronicCare { get; set; }
        public string Risk_Level { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public string Financial_Guarantor_Name { get; set; }
    }
}
