//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    
    public partial class PatientInsuranceViewModel
    {
        public long Patient_Insurance_Id { get; set; }
        public Nullable<long> Patient_Account { get; set; }
        public long Insurance_Id { get; set; }
        public string Pri_Sec_Oth_Type { get; set; }
        public Nullable<decimal> Co_Payment { get; set; }
        public Nullable<decimal> Deductions { get; set; }
        public string Policy_Number { get; set; }
        public string Group_Number { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public Nullable<System.DateTime> Termination_Date { get; set; }
        public Nullable<long> Subscriber { get; set; }
        public string Relationship { get; set; }
        public string Eligibility_Status { get; set; }
        public Nullable<long> Eligibility_S_No { get; set; }
        public Nullable<System.DateTime> Eligibility_Enquiry_Date { get; set; }
        public string Access_Carolina_Number { get; set; }
        public Nullable<bool> Is_Capitated_Patient { get; set; }
        public Nullable<int> Allowed_Visits { get; set; }
        public Nullable<int> Remaining_Visits { get; set; }
        public Nullable<System.DateTime> Visits_Start_Date { get; set; }
        public Nullable<System.DateTime> Visits_End_Date { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string CCN { get; set; }
        public string Group_Name { get; set; }
        public string Created_From { get; set; }
        public string MCR_Sec_Payer { get; set; }
        public Nullable<long> MCR_Sec_Payer_Code { get; set; }
        public string Eligibility_Difference { get; set; }
        public string Filing_Indicator_Code { get; set; }
        public string Filing_Indicator { get; set; }
        public string Plan_type { get; set; }
        public string coverage_description { get; set; }
        public Nullable<int> Co_Payment_Per { get; set; }
        public string Plan_Name { get; set; }
        public string Plan_Name_Type { get; set; }
        public string PayerDescription { get; set; }
    }
}
