//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPaymentProcessed
    {
        public long PatientPaymentProcessed_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> date_scheduled { get; set; }
        public Nullable<long> patient_payment_info_id { get; set; }
        public Nullable<int> payment_plan_length { get; set; }
        public Nullable<int> payment_plan_id { get; set; }
        public string status { get; set; }
        public Nullable<bool> is_successful { get; set; }
        public Nullable<System.DateTime> submitted_at { get; set; }
        public Nullable<long> transfer_id { get; set; }
        public Nullable<System.DateTime> date_cancelled { get; set; }
        public string card_brand { get; set; }
        public Nullable<long> bank_number { get; set; }
        public string payment_method_type { get; set; }
        public string description { get; set; }
        public Nullable<long> batch_number { get; set; }
        public Nullable<long> secondary_patient_payment_info_id { get; set; }
        public Nullable<long> created_by_user_id { get; set; }
        public Nullable<decimal> total_fee { get; set; }
        public Nullable<decimal> expected_amount_cents { get; set; }
        public Nullable<decimal> refunded_amount { get; set; }
        public Nullable<decimal> adjusted_fee { get; set; }
        public Nullable<long> enterprise_id { get; set; }
        public Nullable<long> patient_id { get; set; }
        public Nullable<System.DateTime> transferred_at { get; set; }
        public string gift_card_number { get; set; }
        public Nullable<decimal> applied_amount { get; set; }
        public Nullable<long> practice_id { get; set; }
        public Nullable<long> doctor_id { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<bool> signed { get; set; }
        public string dispute_status { get; set; }
        public Nullable<long> dispute_id { get; set; }
        public Nullable<decimal> reversal_amount { get; set; }
        public string payer_description { get; set; }
        public Nullable<long> merged_payment_id { get; set; }
        public Nullable<long> deposit_account_id { get; set; }
        public string sub_type { get; set; }
        public Nullable<bool> is_posting { get; set; }
        public string last_4_digits { get; set; }
        public Nullable<bool> has_attachments { get; set; }
        public Nullable<bool> can_change_submitted_at_date { get; set; }
        public Nullable<bool> is_archive_pending { get; set; }
    }
}
