//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHARMACy
    {
        public long PHARMACY_CODE { get; set; }
        public string PHARMACY_NAME { get; set; }
        public string PHARMACY_ADDRESS { get; set; }
        public string PHARMACY_CITY { get; set; }
        public string PHARMACY_STATE { get; set; }
        public string PHARMACY_ZIP { get; set; }
        public string PHARMACY_PHONE { get; set; }
        public string PHARMACY_FAX { get; set; }
        public string PHARMACY_EMAIL { get; set; }
        public string PHARMACY_URL { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<bool> IS_DEMO { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public string NCPDPID { get; set; }
        public string StoreNumber { get; set; }
        public string ReferenceNumberAlt1 { get; set; }
        public string ReferenceNumberAlt1Qualifier { get; set; }
        public string StoreName { get; set; }
        public string PhoneAlt1 { get; set; }
        public string PhoneAlt1Qualifier { get; set; }
        public string PhoneAlt2 { get; set; }
        public string PhoneAlt2Qualifier { get; set; }
        public string PhoneAlt3 { get; set; }
        public string PhoneAlt3Qualifier { get; set; }
        public string PhoneAlt4 { get; set; }
        public string PhoneAlt4Qualifier { get; set; }
        public string PhoneAlt5 { get; set; }
        public string PhoneAlt5Qualifier { get; set; }
        public Nullable<System.DateTime> ActiveStartTime { get; set; }
        public Nullable<System.DateTime> ActiveEndTime { get; set; }
        public string ServiceLevel { get; set; }
        public string PartnerAccount { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string TwentyFourHourFlag { get; set; }
        public string CrossStreet { get; set; }
        public string RecordChange { get; set; }
        public string OldServiceLevel { get; set; }
        public string TextServiceLevel { get; set; }
        public string TextServiceLevelChange { get; set; }
        public string Version { get; set; }
        public string NPI { get; set; }
        public string SpecialtyType1 { get; set; }
        public string SpecialtyType2 { get; set; }
        public string SpecialtyType3 { get; set; }
        public string SpecialtyType4 { get; set; }
        public string FileID { get; set; }
        public string StateLicenseNumber { get; set; }
        public string MedicareNumber { get; set; }
        public string MedicaidNumber { get; set; }
        public string PPONumber { get; set; }
        public string PayerID { get; set; }
        public string BINLocationNumber { get; set; }
        public string DEANumber { get; set; }
        public string HIN { get; set; }
        public string SecondaryCoverage { get; set; }
        public string NAICCode { get; set; }
        public string PromotionNumber { get; set; }
        public string SocialSecurity { get; set; }
        public string PriorAuthorization { get; set; }
        public string MutuallyDefined { get; set; }
        public string PHARMACY_ADDRESS_LINE2 { get; set; }
        public string IsValid { get; set; }
    }
}
