//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHY_BA_AGREEMENT
    {
        public long AGREEMENT_ID { get; set; }
        public Nullable<System.DateTime> AGREEMENT_DATETIME { get; set; }
        public string AGREEMENT_USER { get; set; }
        public string USER_IP { get; set; }
        public string AGREEMENT_VERSION { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string TITLE { get; set; }
        public long PRACTICE_CODE { get; set; }
    }
}
