//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class physcian_information
    {
        public string user_name { get; set; }
        public int row_id { get; set; }
        public string Phy_Info_First_Name { get; set; }
        public string Phy_Info_MI { get; set; }
        public string Phy_Info_Last_Name { get; set; }
        public string Phy_Info_Credentials { get; set; }
        public string Phy_Info_Speciality { get; set; }
        public string Phy_Info_Soc_Sec { get; set; }
        public string Phy_Info_DOB { get; set; }
        public string Phy_Info_Office_Tel { get; set; }
        public string Phy_Info_Cell_Phone { get; set; }
        public string Phy_Info_Pager { get; set; }
        public string Phy_Info_Email { get; set; }
        public string Phy_Info_Provider_NPI { get; set; }
        public string Phy_Info_Dea { get; set; }
        public string Phy_Info_Dea_Expiry_Date { get; set; }
        public string Phy_Info_License_No { get; set; }
        public string FileUpload1 { get; set; }
        public string Phy_Info_Upin { get; set; }
        public string Phy_Info_Clia { get; set; }
        public string FileUpload2 { get; set; }
        public string Phy_Info_Clia_Expiry_Date { get; set; }
    }
}
