//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class place_of_services_bkp_11082018
    {
        public string POS_Code { get; set; }
        public string POS_Name { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public System.DateTime Sync_Date { get; set; }
        public Nullable<bool> Facility_Required { get; set; }
        public Nullable<bool> FromTo_DateRequired { get; set; }
    }
}
