//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_setup
    {
        public long Plan_Code { get; set; }
        public string Plan_Name { get; set; }
        public string Plan_Address { get; set; }
        public string Plan_City { get; set; }
        public string Plan_State { get; set; }
        public string Plan_ZIP { get; set; }
        public string Plan_Contact_Name { get; set; }
        public string Plan_Phone { get; set; }
        public string Plan_Type { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<long> MTBC_Code { get; set; }
        public System.DateTime Sync_Date { get; set; }
        public string NPI { get; set; }
        public string Plan_id_number { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public string Accession { get; set; }
    }
}
