//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Possible_Options
    {
        public int Possible_Options_ID { get; set; }
        public Nullable<int> Questions_ID { get; set; }
        public Nullable<int> Option_Sequence { get; set; }
        public string Possible_Options_Details { get; set; }
        public Nullable<int> Correct_Option { get; set; }
        public string Test_Details_ID { get; set; }
    }
}
