//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public long post_id { get; set; }
        public string post_Title { get; set; }
        public string post_description { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public string user_name { get; set; }
        public Nullable<long> thread_id { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string post_reply { get; set; }
        public Nullable<bool> Is_Block { get; set; }
        public string Created_By { get; set; }
        public string attachments { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Source { get; set; }
        public string ForumUserName { get; set; }
    }
}
