//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_Groups
    {
        public int GROUP_ID { get; set; }
        public string PRACTICE_CODE { get; set; }
        public string GROUP_NAME { get; set; }
        public string GROUP_TYPE { get; set; }
    }
}
