//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_SignUp_Contact_Information
    {
        public long Physician_ID { get; set; }
        public string Practice_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_Initial { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string SSN { get; set; }
        public string Home_Fax { get; set; }
        public string Home_Telephone { get; set; }
        public string Cell_Phone { get; set; }
        public string Gender { get; set; }
        public string Physician_Speciality { get; set; }
        public string Street_Address { get; set; }
        public string Practice_City { get; set; }
        public string Practice_State { get; set; }
        public string Practice_Zip { get; set; }
        public string Office_Telephone { get; set; }
        public string Office_Fax { get; set; }
        public string Back_Line { get; set; }
        public string Pager { get; set; }
        public string EMail_Address { get; set; }
        public string Office_Manager { get; set; }
        public string DEA_Number { get; set; }
        public Nullable<System.DateTime> DEA_ExpiryDate { get; set; }
        public string License_Number { get; set; }
        public string Tax_ID { get; set; }
        public string UPIN_Number { get; set; }
        public string Clia_Number { get; set; }
        public string Practice_Type { get; set; }
        public string Client_IPAddress { get; set; }
        public string Client_TimeZone { get; set; }
        public string Client_Date { get; set; }
        public string Server_Time { get; set; }
        public string Server_Date { get; set; }
        public string Contact_Time { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public Nullable<int> Practice_Status { get; set; }
        public string Status_Information { get; set; }
        public string Additional_Information { get; set; }
    }
}
