//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_Contract
    {
        public long Contract_ID { get; set; }
        public string WelcomeCall { get; set; }
        public string EnrollmentTracker { get; set; }
        public Nullable<System.DateTime> WelcomeCallDate { get; set; }
        public Nullable<System.DateTime> EnrollmentTrackerDate { get; set; }
        public string CallsCompleted { get; set; }
        public Nullable<System.DateTime> CallsCompletedDate { get; set; }
        public string DataExportCompleted { get; set; }
        public Nullable<System.DateTime> DataExportCompletedDate { get; set; }
        public string TrainingScheduled { get; set; }
        public string TrainingCompleted { get; set; }
        public Nullable<System.DateTime> TrainingCompletedDate { get; set; }
        public string Completed { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string BillingSent { get; set; }
        public Nullable<System.DateTime> BillingSetDate { get; set; }
        public string FirstStepRemarks { get; set; }
        public string EnrollmentCallsRemarks { get; set; }
        public string DataExportRemarks { get; set; }
        public string TrainingRemarks { get; set; }
        public string InterfaceRemarks { get; set; }
        public string FirstBillingRemarks { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<long> Sales_ID { get; set; }
        public string Status { get; set; }
    }
}
