//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACTICE_DIVISION
    {
        public long practice_code { get; set; }
        public int Server_id { get; set; }
        public Nullable<int> eob_received { get; set; }
        public Nullable<bool> fee_schedule { get; set; }
        public string is_newsite { get; set; }
        public Nullable<bool> Is_EMR_Active { get; set; }
        public Nullable<System.DateTime> WebEHR_Active_Date { get; set; }
        public Nullable<System.DateTime> WebEHR_InActive_Date { get; set; }
        public string Comments { get; set; }
        public string SERVERNAME { get; set; }
        public string WEBSERVER_NAME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
