//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_Daily_Missing_Work
    {
        public long Practice_Code { get; set; }
        public Nullable<System.DateTime> Missing_DOS { get; set; }
        public string User_Remarks { get; set; }
        public string Doctor_Feedback { get; set; }
        public string Status { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string doctor_other_feedback { get; set; }
        public long Location_Code { get; set; }
    }
}
