//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeSynchronization
    {
        public long PracticeSyncId { get; set; }
        public long PracticeId { get; set; }
        public Nullable<System.DateTimeOffset> StartedAt { get; set; }
        public Nullable<System.DateTimeOffset> CompletedAt { get; set; }
        public long SynchronizedBy { get; set; }
        public Nullable<int> SynchronizationProgress { get; set; }
        public Nullable<bool> IsFailed { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDate { get; set; }
    }
}
