//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_SignUp_Physician_Facilities_Info
    {
        public long Facility_ID { get; set; }
        public string Facility_Name { get; set; }
        public string Facility_Number { get; set; }
        public string Phone_No { get; set; }
        public Nullable<long> Physician_ID { get; set; }
    }
}
