//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_SignUp_Daily_Office_Hours
    {
        public long OfficeHr_ID { get; set; }
        public Nullable<long> Physician_ID { get; set; }
        public string Day { get; set; }
        public string From_Time { get; set; }
        public string To_Time { get; set; }
    }
}
