//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_Special_Instruction_Answers
    {
        public long Practice_Code { get; set; }
        public long Question_Id { get; set; }
        public string Special_Instruction { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modify_By { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public string Reference_Instruction_ID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Expired { get; set; }
        public Nullable<System.DateTime> Expired_Date { get; set; }
        public Nullable<long> Template_ID { get; set; }
    }
}
