//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practices_Techincal_Information
    {
        public long VendorId { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public Nullable<long> Provider_Code { get; set; }
        public string VendorName { get; set; }
        public string Internet_UploadSpeed { get; set; }
        public string Internet_DownloadSpeed { get; set; }
        public string No_of_Desktop_Computers { get; set; }
        public string No_of_Laptops { get; set; }
        public string No_of_IPADS { get; set; }
        public string No_of_Scanner { get; set; }
        public string No_of_Printers { get; set; }
        public string LinkToLAN { get; set; }
        public string Other_Info { get; set; }
        public string Using_EHR { get; set; }
        public string No_of_IT_Person { get; set; }
        public string IT_Person_Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Type_of_LAN { get; set; }
        public string Users { get; set; }
    }
}
