//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_Locations
    {
        public long Location_Code { get; set; }
        public string Location_Name { get; set; }
        public long Practice_Code { get; set; }
        public string Location_Address { get; set; }
        public string Location_City { get; set; }
        public string Location_State { get; set; }
        public string Location_Zip { get; set; }
        public string Location_Short { get; set; }
        public string Clia_Number { get; set; }
        public Nullable<System.DateTime> Clia_Expiry_Date { get; set; }
        public string Phone_one { get; set; }
        public string Phone_two { get; set; }
        public string phone_type_one { get; set; }
        public string phone_type_two { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Phone_Ext_One { get; set; }
        public string Phone_Ext_Two { get; set; }
        public string Location_ID { get; set; }
        public string NPI { get; set; }
        public Nullable<bool> is_default { get; set; }
    }
}
