//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prac_TermDate_Process
    {
        public long Prac_TermDate_Process_Id { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public Nullable<long> Prac_TermDate_Steps_Id { get; set; }
        public Nullable<bool> Email_Sent { get; set; }
        public Nullable<bool> Case_Generated { get; set; }
        public string Case_No { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Performed_OP { get; set; }
    }
}
