//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_SignUp_Insurance_Information
    {
        public long Insurance_ID { get; set; }
        public Nullable<long> Physician_ID { get; set; }
        public string Insurance_Name { get; set; }
        public string Provider_ID { get; set; }
        public string Group_ID { get; set; }
        public string Group_Suffix { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public string Participating_Status { get; set; }
    }
}
