//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACTICE_PROCEDURE1
    {
        public string PRACTICE_CODE { get; set; }
        public string PROC_CODE { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<bool> Collective { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODFIED_DATE { get; set; }
        public string ISREPLICATED { get; set; }
        public Nullable<bool> additional { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> Topones { get; set; }
        public Nullable<long> id { get; set; }
    }
}
