//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_Locations_Plan_Group
    {
        public long S_No { get; set; }
        public Nullable<long> Group_ID { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public string Group_Name { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modfied_Date { get; set; }
        public string Modfied_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<double> Percentage { get; set; }
    }
}
