//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_NPI_confirmation
    {
        public int Serial__No { get; set; }
        public string Practice_code { get; set; }
        public string Practice_Name { get; set; }
        public string Practice_NPI { get; set; }
        public string Provider_code { get; set; }
        public string Provider_Name { get; set; }
        public string Provider_NPI { get; set; }
        public Nullable<bool> Corect_Incorrect { get; set; }
        public string Feedback { get; set; }
        public string Feedback_entered_by { get; set; }
        public Nullable<System.DateTime> Feedback_date { get; set; }
    }
}
