//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_Special_Instruction_AnswersReview
    {
        public string INSTRUCTION_ID { get; set; }
        public string QUESTION { get; set; }
        public string REVIEWED_ANS { get; set; }
        public string PUBLISHED_ANS { get; set; }
        public string REVIEWED_BY_MO { get; set; }
        public string MO_REMARKS { get; set; }
        public string REVIEWED_BY_COMPLAINS { get; set; }
        public string COMPLAINS_REMARKS { get; set; }
        public string REVIEWED_BY_NASD { get; set; }
        public string NASD_REMARKS { get; set; }
        public string REVIEWED_BY_FPBA { get; set; }
        public string EXPRESSIONS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<long> question_no { get; set; }
        public Nullable<long> Practice_code { get; set; }
        public Nullable<long> Category_Id { get; set; }
        public Nullable<long> QUESTION_Id { get; set; }
        public Nullable<bool> Published_Now { get; set; }
        public string Published_Type { get; set; }
        public string Mo_Name { get; set; }
        public Nullable<System.DateTime> Mo_Review_Date { get; set; }
        public string Complains_Name { get; set; }
        public Nullable<System.DateTime> Complains_Review_Date { get; set; }
        public string NASD_Name { get; set; }
        public Nullable<System.DateTime> NASD_Review_Date { get; set; }
        public string FPBA_Name { get; set; }
        public Nullable<System.DateTime> FPBA_Review_Date { get; set; }
        public Nullable<bool> Done { get; set; }
        public string suggested_instruction { get; set; }
        public Nullable<long> InsPayer_Id { get; set; }
        public string Specialization_Code { get; set; }
        public string Case_No { get; set; }
        public Nullable<bool> Show_On_Web_MO { get; set; }
        public Nullable<bool> Show_On_Web_COMPLAINS { get; set; }
        public string Reviewed_by_TL { get; set; }
        public Nullable<System.DateTime> TL_Review_Date { get; set; }
        public string TL_Remarks { get; set; }
        public string TL_name { get; set; }
        public string TL_Revised { get; set; }
        public Nullable<System.DateTime> TL_Revised_Date { get; set; }
        public string TL_Revise_Name { get; set; }
        public Nullable<long> Template_ID { get; set; }
        public string reference_no { get; set; }
    }
}
