//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_SMS_Settings
    {
        public long SMS_Setting_Id { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public Nullable<long> Provider_Code { get; set; }
        public string Phone_Number { get; set; }
        public string Subscription_Type { get; set; }
        public Nullable<long> Services { get; set; }
        public string User_Name { get; set; }
        public string Monday { get; set; }
        public string Tuesday { get; set; }
        public string Wednesday { get; set; }
        public string Thursday { get; set; }
        public string Friday { get; set; }
        public string Saturday { get; set; }
        public string Sunday { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Subscription_Start_Date { get; set; }
        public Nullable<System.DateTime> Subscription_End_Date { get; set; }
        public string Comments { get; set; }
        public string Subscription_Status { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Activation_Code { get; set; }
    }
}
