//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACTICE_FACILITY
    {
        public long Practice_Code { get; set; }
        public long Facility_Code { get; set; }
        public Nullable<long> HL7_Facility_Code { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> POS { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public int Created_By { get; set; }
        public System.DateTimeOffset Created_Date { get; set; }
        public int Modified_By { get; set; }
        public System.DateTimeOffset Modified_Date { get; set; }
    }
}
