//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class practice_information
    {
        public string user_name { get; set; }
        public string practice_name { get; set; }
        public string taxid { get; set; }
        public string practicetype { get; set; }
        public string physcianno { get; set; }
        public string groupnpi { get; set; }
        public string physcial_address { get; set; }
        public string physcial_city { get; set; }
        public string physcial_state { get; set; }
        public string physcial_zip { get; set; }
        public string physcial_officetel { get; set; }
        public string physcial_privateliine { get; set; }
        public string physcial_officefax { get; set; }
        public string physcial_emailaddress { get; set; }
        public Nullable<int> billing_yes { get; set; }
        public string billing_address { get; set; }
        public string billing_city { get; set; }
        public string billing_state { get; set; }
        public string billing_zip { get; set; }
        public Nullable<int> location_number { get; set; }
        public string office_contact { get; set; }
        public string office_email { get; set; }
        public string office_tel { get; set; }
        public string financial_contact { get; set; }
        public string financial_email { get; set; }
        public string financial_tel { get; set; }
        public string financial_fax { get; set; }
    }
}
