//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeAppointmentReason
    {
        public long PracAppReasonID { get; set; }
        public long Practice_Code { get; set; }
        public Nullable<long> PROVIDER_CODE { get; set; }
        public Nullable<long> LOCATION_ID { get; set; }
        public long Reason_Id { get; set; }
        public string REASON_COLOR { get; set; }
        public Nullable<long> created_by { get; set; }
        public System.DateTimeOffset created_date { get; set; }
        public Nullable<long> modified_by { get; set; }
        public Nullable<System.DateTimeOffset> modified_date { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
