//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeAppointmentStatu
    {
        public long PracAppSID { get; set; }
        public Nullable<long> PracCode { get; set; }
        public Nullable<long> ProvdID { get; set; }
        public Nullable<long> LocID { get; set; }
        public Nullable<long> AppStatusID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public System.DateTimeOffset CREATED_DATE { get; set; }
        public Nullable<long> MODIFIED_BY { get; set; }
        public System.DateTimeOffset MODIFIED_DATE { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
