//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_Notes
    {
        public long PRACTICE_Code { get; set; }
        public System.DateTime NOTE_DATE { get; set; }
        public string NOTE_CONTENT { get; set; }
        public string NOTE_USER { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public long Practice_Notes_Id { get; set; }
    }
}
