//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeSynchronizationLog
    {
        public long LogId { get; set; }
        public Nullable<long> PracticeSyncId { get; set; }
        public string LogMessage { get; set; }
        public Nullable<System.DateTimeOffset> LogTime { get; set; }
    }
}
