//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prac_Term_Date_Steps
    {
        public long Practice_TermDate_Steps_Id { get; set; }
        public string Steps_Name { get; set; }
        public Nullable<long> No_Of_Days { get; set; }
        public Nullable<bool> Cases { get; set; }
        public Nullable<bool> E_Mail { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
