//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_Transcription_Amount
    {
        public long Practice { get; set; }
        public int Files { get; set; }
        public int Characters { get; set; }
        public int Lines { get; set; }
        public decimal Amount { get; set; }
        public string month { get; set; }
        public string Year { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public bool Deleted { get; set; }
    }
}
