//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCEDURES_ALERTS
    {
        public long PROC_ALERT_ID { get; set; }
        public string PROC_CODE { get; set; }
        public string PROC_ALERT_DESCRIPTION { get; set; }
        public Nullable<bool> IS_PROMPT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<long> Practice_Code { get; set; }
    }
}
