//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_US_Holidays
    {
        public int USHoliday_id { get; set; }
        public long Provider_code { get; set; }
        public bool IsWorkingDay { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public long Location_code { get; set; }
        public System.DateTime Sync_Date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string old_usHoliday_id { get; set; }
        public long practice_code { get; set; }
    }
}
