//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Year_Holidays
    {
        public long Holiday_id { get; set; }
        public long Practice_Code { get; set; }
        public long Provider_code { get; set; }
        public long Location_Code { get; set; }
        public Nullable<System.DateTime> Holiday_From { get; set; }
        public Nullable<System.DateTime> Holiday_To { get; set; }
        public string Holiday_title { get; set; }
        public Nullable<System.DateTimeOffset> Created_date { get; set; }
        public Nullable<long> Created_by { get; set; }
        public Nullable<System.DateTimeOffset> Modified_date { get; set; }
        public Nullable<long> Modified_by { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> Holiday_date { get; set; }
    }
}
