//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Oncall
    {
        public Nullable<long> Provider_Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> oncall { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public Nullable<long> Location_Code { get; set; }
        public Nullable<bool> offday { get; set; }
        public string Day { get; set; }
        public long provider_oncall_id { get; set; }
        public string COMMENTS { get; set; }
    }
}
