//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Appointment_Rules
    {
        public long Rule_id { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public long Provider_code { get; set; }
        public Nullable<System.DateTime> No_Appointments_Start_Time { get; set; }
        public Nullable<System.DateTime> No_Appointment_End_Time { get; set; }
        public Nullable<int> Max_New_Patients_Row { get; set; }
        public Nullable<int> Max_Old_Patients_Row { get; set; }
        public Nullable<int> Per_Day_new_Patients { get; set; }
        public Nullable<int> Per_Day_old_Patients { get; set; }
        public Nullable<int> Time_Slot_Size { get; set; }
        public Nullable<int> Max_Office_Visits { get; set; }
        public Nullable<bool> Dont_Logoff_Schedular { get; set; }
        public Nullable<int> Auto_Logout_Time { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<long> Location_code { get; set; }
        public Nullable<long> Default_Reason { get; set; }
        public Nullable<bool> multiple_appointment { get; set; }
        public Nullable<int> Critical_Reminder { get; set; }
        public Nullable<int> Medium_Reminder { get; set; }
        public Nullable<int> Normal_Reminder { get; set; }
        public Nullable<short> No_Multiple_App { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public Nullable<bool> emergency_call { get; set; }
        public string emergency_call_number { get; set; }
        public Nullable<bool> multiple_breaks { get; set; }
        public Nullable<bool> multiple_time_slots { get; set; }
        public Nullable<bool> under_eighteen_message { get; set; }
        public Nullable<bool> no_show_cancel_resch { get; set; }
        public Nullable<bool> follow_up_appointment { get; set; }
        public Nullable<bool> NOTES_FOR_IOU { get; set; }
        public string NOTES_FOR_IOU_TEXT { get; set; }
        public string PROVIDER_COLOR { get; set; }
        public string ARRIVED_COLOR { get; set; }
        public Nullable<bool> Is_Offday_Working { get; set; }
        public Nullable<bool> is_app_overlapping_allowed { get; set; }
        public Nullable<bool> is_system_created_claim { get; set; }
        public Nullable<bool> ShowTeleHealthSession { get; set; }
        public Nullable<bool> APPOINTMENT_REMINDER_SETTING { get; set; }
        public Nullable<bool> DEFAULT_PATIENT_SETTING { get; set; }
    }
}
