//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVIDER_PAYER_PRINTCENTER
    {
        public long ID { get; set; }
        public string Auth_By { get; set; }
        public Nullable<System.DateTime> Auth_Date { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Location_Code { get; set; }
        public string Provider_Code { get; set; }
        public string Payer_Id { get; set; }
    }
}
