//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Cpt_Plan_Notes
    {
        public long Note_Id { get; set; }
        public string Provider_Cpt_Plan_Id { get; set; }
        public System.DateTime NOTE_DATE { get; set; }
        public string NOTE_CONTENT { get; set; }
        public string NOTE_USER { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTimeOffset> CREATED_DATE { get; set; }
        public Nullable<long> MODIFIED_BY { get; set; }
        public Nullable<System.DateTimeOffset> MODIFIED_DATE { get; set; }
    }
}
