//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Diagnosis
    {
        public long Provider_Diag_Id { get; set; }
        public string Diag_Code { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public Nullable<long> Provider_Code { get; set; }
        public Nullable<bool> Collective { get; set; }
        public Nullable<System.DateTimeOffset> CREATED_Dtae { get; set; }
        public Nullable<long> CREATED_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<bool> Additional { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> SerialNumber { get; set; }
        public Nullable<int> Provider_Diag_Group_Id { get; set; }
        public Nullable<bool> Topones { get; set; }
        public Nullable<long> location_code { get; set; }
        public string CODE_TYPE { get; set; }
    }
}
