//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class providers_reasons_timeunits
    {
        public long Practice_code { get; set; }
        public long Provider_code { get; set; }
        public long Location_code { get; set; }
        public long Reason_id { get; set; }
        public long Time_Units { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public System.DateTime Modified_date { get; set; }
        public string Modified_by { get; set; }
    }
}
