//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Working_Days_Time_Temp
    {
        public long Provider_Code { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public Nullable<short> WorkDay_Option_Id { get; set; }
        public Nullable<long> Location_Code { get; set; }
        public string Weekday_Id { get; set; }
        public Nullable<System.DateTime> Time_From { get; set; }
        public Nullable<System.DateTime> Time_To { get; set; }
        public Nullable<System.DateTime> Break_Time_From { get; set; }
        public Nullable<System.DateTime> Break_Time_To { get; set; }
        public Nullable<bool> Enable_Break { get; set; }
        public Nullable<System.DateTime> Date_From { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Day_On { get; set; }
        public long provider_working_days_time_temp_id { get; set; }
        public System.DateTime sync_date { get; set; }
        public Nullable<System.DateTime> Date_To { get; set; }
        public Nullable<int> Time_slot_size { get; set; }
        public Nullable<bool> DELETED { get; set; }
    }
}
