//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Resources
    {
        public int Resource_Id { get; set; }
        public long Provider_Code { get; set; }
        public string Insurance_Name { get; set; }
        public string User_Id { get; set; }
        public string Password { get; set; }
        public string URL { get; set; }
        public string ARU { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> In_Active { get; set; }
        public Nullable<int> Expiry_Days { get; set; }
        public Nullable<long> Modified_Expiry_Date_By { get; set; }
        public Nullable<System.DateTime> Modified_Expiry_Date { get; set; }
        public string Login_Type { get; set; }
        public Nullable<long> InsPayer_Id { get; set; }
        public Nullable<long> InsName_Id { get; set; }
    }
}
