//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Resource_Mapping
    {
        public long Map_Id { get; set; }
        public Nullable<long> Resource_Id { get; set; }
        public Nullable<long> Insname_Id { get; set; }
        public Nullable<long> Inspayer_Id { get; set; }
        public int deleted { get; set; }
    }
}
