//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVIDER_PROCEDURES
    {
        public long PROVIDER_PROC_ID { get; set; }
        public string PROC_CODE { get; set; }
        public Nullable<long> PROVIDER_CODE { get; set; }
        public Nullable<long> PRACTICE_CODE { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<bool> Collective { get; set; }
        public Nullable<System.DateTime> CREATED_DTAE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<bool> additional { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> SerialNumber { get; set; }
        public Nullable<int> PROVIDER_PROC_GROUP_ID { get; set; }
        public Nullable<bool> TOPONES { get; set; }
        public Nullable<long> location_code { get; set; }
    }
}
