//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Payers
    {
        public long Provider_Code { get; set; }
        public long InsPayer_Id { get; set; }
        public string Provider_Payer_Id { get; set; }
        public string Provider_Payer_Group { get; set; }
        public string Group_Suffix { get; set; }
        public Nullable<bool> Include_In_EDI { get; set; }
        public Nullable<bool> Is_Participating { get; set; }
        public Nullable<bool> Print_Center { get; set; }
        public string SSN { get; set; }
        public string EIN { get; set; }
        public string Clia_No { get; set; }
        public Nullable<bool> Is_Capitation { get; set; }
        public string Prac_Type { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public long Location_Code { get; set; }
        public Nullable<bool> Include_In_Eligibility { get; set; }
        public Nullable<bool> Include_In_SDF { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Billing_Practice_Name { get; set; }
        public Nullable<bool> Is_Eligibility_Cascaded_Payer { get; set; }
        public string user_notes { get; set; }
        public string Individual_NPI { get; set; }
        public string Group_NPI { get; set; }
        public Nullable<bool> Pt_Billing_Allowed { get; set; }
        public string Submitter_ID { get; set; }
        public string Reciever_ID { get; set; }
        public string GS02 { get; set; }
        public string GS03 { get; set; }
        public string NM109_1000A { get; set; }
        public Nullable<bool> Stop_Billing { get; set; }
        public Nullable<bool> Credentialing { get; set; }
        public string NM103_1000A { get; set; }
        public string Pay_To_Provider_Npi { get; set; }
        public Nullable<bool> EDISetupRequired { get; set; }
        public string Pay_To_Address { get; set; }
        public string Pay_To_Zip { get; set; }
        public string Pay_To_City { get; set; }
        public string Pay_To_State { get; set; }
        public string Rendering_Prov_Taxonomy { get; set; }
        public Nullable<System.DateTime> Credentialing_Date { get; set; }
        public Nullable<bool> Allow_Non_Par_Elig { get; set; }
        public Nullable<System.DateTime> Credentialing_Expiry_Date { get; set; }
        public Nullable<bool> EDI_Setup_Pending { get; set; }
        public string ClamStatus_NPI { get; set; }
        public string Payer_Emc_number { get; set; }
        public string Submitter_Contact_Person { get; set; }
        public string Submitter_Contact_Number { get; set; }
        public string Era_Setup { get; set; }
        public Nullable<long> Submission_Setup_Id { get; set; }
        public string Stop_Submission_Reasons { get; set; }
        public string Stop_Submission_Reasons_Department { get; set; }
        public Nullable<System.DateTime> Era_Setup_Date { get; set; }
        public string EDI_Reason { get; set; }
        public Nullable<bool> Credentialing_Completed { get; set; }
        public Nullable<System.DateTime> Credentialing_Application_Date { get; set; }
        public Nullable<System.DateTime> Credentialing_Effective_Date { get; set; }
        public Nullable<bool> Enrollment_In_Process { get; set; }
        public string BANK_ACCOUNT_NUMBER { get; set; }
        public string BANK_ROUTING_NUMBER { get; set; }
        public Nullable<long> DESTINATION_SERVER { get; set; }
        public string ELIGIBILITY_NPI { get; set; }
        public string ERA_EFT_STATUS { get; set; }
        public Nullable<bool> HISTORY { get; set; }
        public Nullable<int> MIN_PAT_BALANCE { get; set; }
        public Nullable<bool> STOP_BRC { get; set; }
        public Nullable<bool> TRAIL_SUBMISSION { get; set; }
        public Nullable<System.DateTime> TRAIL_SUBMISSION_DATE { get; set; }
    }
}
