//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ptl_Description
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public string Desc_Type { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> WebResolve { get; set; }
        public Nullable<bool> DisableUserNotes { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public Nullable<bool> Is_mandatory { get; set; }
        public Nullable<bool> ATTACHMENT_REQ { get; set; }
    }
}
