//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptl_filing_limit
    {
        public Nullable<long> Practice_Code { get; set; }
        public long Claim_No { get; set; }
        public string s { get; set; }
        public long patient_account { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string MI { get; set; }
        public string Scan_No { get; set; }
        public string city { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Address { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string SSN { get; set; }
        public string Marital_Status { get; set; }
        public string Gender { get; set; }
        public string Home_Phone { get; set; }
        public string Business_Phone { get; set; }
        public bool PPS { get; set; }
        public bool CPS { get; set; }
        public string PA_Number { get; set; }
        public Nullable<long> Referring_Physician { get; set; }
        public Nullable<System.DateTime> Hospital_From { get; set; }
        public Nullable<System.DateTime> Hospital_To { get; set; }
        public Nullable<long> Facility_Code { get; set; }
        public string facility_name { get; set; }
        public Nullable<int> No_of_Days { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string pri_status { get; set; }
        public string sec_status { get; set; }
        public string oth_status { get; set; }
        public Nullable<long> insurance1 { get; set; }
        public int limitCount { get; set; }
        public Nullable<int> difference1 { get; set; }
        public string Limit1 { get; set; }
    }
}
