//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral_Physicians
    {
        public long Referral_Code { get; set; }
        public string Referral_Lname { get; set; }
        public string Referral_Fname { get; set; }
        public string Referral_Mi { get; set; }
        public string Referral_Address { get; set; }
        public string Referral_City { get; set; }
        public string Referral_State { get; set; }
        public string Referral_Zip { get; set; }
        public string Referral_Phone { get; set; }
        public string Referral_Contact_Person { get; set; }
        public string Referral_Tax_Id { get; set; }
        public string Referral_License { get; set; }
        public string Referral_Upin { get; set; }
        public string Referral_Ssn { get; set; }
        public string Referral_Taxonomy_Code { get; set; }
        public Nullable<bool> Exported { get; set; }
        public Nullable<bool> Recent_Use { get; set; }
        public Nullable<System.DateTime> Export_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
        public string Pin { get; set; }
        public string NPI { get; set; }
        public string Referral_Fax { get; set; }
        public string Title { get; set; }
        public string Referral_Email { get; set; }
        public Nullable<bool> In_Active { get; set; }
    }
}
