//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_Module_Properties
    {
        public long ROLE_MODULE_PROPERTY_ID { get; set; }
        public long Role_Id { get; set; }
        public long Module_Id { get; set; }
        public long Sub_Module_Id { get; set; }
        public long Property_Id { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
