//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrubberQueue
    {
        public long ClaimNo { get; set; }
        public Nullable<long> PatientAccount { get; set; }
        public Nullable<System.DateTime> AddToQDate { get; set; }
        public Nullable<long> ProviderCode { get; set; }
        public string Status { get; set; }
        public string CPT { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> FailingDate { get; set; }
    }
}
