//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Second_level_rejection
    {
        public long S_No { get; set; }
        public Nullable<long> Claim_No { get; set; }
        public Nullable<System.DateTime> Process_Date { get; set; }
        public string Rejection_Reason { get; set; }
        public Nullable<System.DateTime> Rejection_Date_ { get; set; }
    }
}
