//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class submission_Plan_bkp
    {
        public long Plan_ID { get; set; }
        public string Plan_Name { get; set; }
        public string Plan_Category { get; set; }
        public string Plan_Status { get; set; }
        public Nullable<System.DateTime> Start_Date_Time { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Practices { get; set; }
        public string Providers { get; set; }
        public string claim_status { get; set; }
        public string Payer_Source_Type { get; set; }
        public Nullable<System.DateTime> Bill_Date_From { get; set; }
        public string Bill_Date_To { get; set; }
        public string Inspayer_IDs { get; set; }
        public string Change_Status { get; set; }
        public string Last_Modification_Date { get; set; }
        public string Billing_NPI_Option { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date_Time { get; set; }
        public string Win_User_Name { get; set; }
        public string Win_Host_Name { get; set; }
        public Nullable<System.DateTime> Monday { get; set; }
        public Nullable<System.DateTime> Tuesday { get; set; }
        public Nullable<System.DateTime> Wednesday { get; set; }
        public Nullable<System.DateTime> Thursday { get; set; }
        public Nullable<System.DateTime> Friday { get; set; }
        public Nullable<System.DateTime> Saturday { get; set; }
        public Nullable<System.DateTime> Sunday { get; set; }
        public string Holidays { get; set; }
        public Nullable<int> Max_Tries { get; set; }
        public string Zero_Balance { get; set; }
        public Nullable<bool> With_Bill_Date { get; set; }
        public string Submission_Off_Days { get; set; }
        public string OUTPUT_FILES_PATH { get; set; }
        public Nullable<bool> Auto_Uploading { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public Nullable<long> MAX_FILES { get; set; }
        public string BATCH_INQUIRY { get; set; }
        public string DATE_TYPE { get; set; }
    }
}
