//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission_Schedual
    {
        public long Schedual_ID { get; set; }
        public long Server_ID { get; set; }
        public string Schedual_Name { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Create_By { get; set; }
        public string User_Name { get; set; }
        public string Host_Name { get; set; }
        public Nullable<System.DateTime> Monday { get; set; }
        public Nullable<System.DateTime> Tuesday { get; set; }
        public Nullable<System.DateTime> Wednesday { get; set; }
        public Nullable<System.DateTime> Thursday { get; set; }
        public Nullable<System.DateTime> Friday { get; set; }
        public Nullable<System.DateTime> Saturday { get; set; }
        public Nullable<System.DateTime> Sunday { get; set; }
        public string Holidays { get; set; }
        public string Schedual_Type { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> recursive { get; set; }
        public Nullable<System.DateTime> recursive_time { get; set; }
        public Nullable<int> Max_Tries { get; set; }
    }
}
