//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBMISSION_SETUP
    {
        public long InsPayer_Id { get; set; }
        public string ISA01 { get; set; }
        public string ISA02 { get; set; }
        public string ISA03 { get; set; }
        public string ISA05 { get; set; }
        public string ISA06 { get; set; }
        public string ISA07 { get; set; }
        public string ISA08 { get; set; }
        public string ISA14 { get; set; }
        public string GS02 { get; set; }
        public string GS03 { get; set; }
        public string NM109_1000A { get; set; }
        public string NM103_1000B { get; set; }
        public string NM109_1000B { get; set; }
        public string NM103_2010BB { get; set; }
        public string NM109_2010BB { get; set; }
        public string Setup_Created_By { get; set; }
        public Nullable<System.DateTime> Setup_Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string REPEATATION_CHAR { get; set; }
        public string ELEMENT_SEP { get; set; }
        public string SUBELEMENT_SEP { get; set; }
        public string SEGMENT_SEP { get; set; }
        public Nullable<bool> NEWLINE_WITHORAS_SEGSEP { get; set; }
        public Nullable<long> Destination_Server { get; set; }
        public long SETUP_ID { get; set; }
        public string SETUP_NAME { get; set; }
        public string BILLING_COMPANY { get; set; }
        public string FILE_RECEIVER { get; set; }
        public string SUBMITTER_NAME { get; set; }
        public string RECEIVER_NAME { get; set; }
        public string CONTACT_PERSON_QUALIFIER { get; set; }
        public string CONTACT_PERSON_QUALIFIER1 { get; set; }
        public string CONTACT_PERSON_NUMBER { get; set; }
        public string CONTACT_PERSON_NUMBER1 { get; set; }
        public string SUBMITTER_CONTACT_PERSON { get; set; }
        public string SERVER_TYPE { get; set; }
        public string HTERMINAL_PHONE_NO { get; set; }
        public string URL { get; set; }
        public string FTP_ADDRESS { get; set; }
        public string USER_ID { get; set; }
        public string PASSWORD { get; set; }
        public string SERVER_UPLOAD_PATH { get; set; }
        public string SERVER_DOWNLOAD_PATH { get; set; }
        public string SERVER_NAME { get; set; }
        public string INSPAYER_835_ID { get; set; }
        public string UPLOAD_PORT { get; set; }
        public string DOWNLOAD_PORT { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public string SETUP_TYPE { get; set; }
    }
}
