//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class submission_servers
    {
        public long Server_ID { get; set; }
        public string Server_Name { get; set; }
        public string Server_Type { get; set; }
        public string Phone_No { get; set; }
        public string URL { get; set; }
        public string FTP_Address { get; set; }
        public string User_ID { get; set; }
        public string Password { get; set; }
        public string Upload_Path { get; set; }
        public string DownLoad_Path { get; set; }
        public long Port_No { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Server_Upload_Path { get; set; }
        public string Server_Download_Path { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Host_Name { get; set; }
        public string User_Name { get; set; }
        public Nullable<bool> IS_Active { get; set; }
        public string KEY_NAMES { get; set; }
    }
}
