//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        public long TASK_USER_ID { get; set; }
        public long TASK_ID { get; set; }
        public string SUBJECT { get; set; }
        public long CATEGORY_ID { get; set; }
        public string PRIORITY { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string PERCENTAGE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> IS_REMINDER { get; set; }
        public Nullable<System.DateTime> REMINDER_TIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<bool> Allow_Forward { get; set; }
        public string User_id { get; set; }
        public string TASK_STATUS { get; set; }
        public Nullable<long> PRACTICE_CODE { get; set; }
        public Nullable<System.DateTime> SNOOZE_REMINDER_TIME { get; set; }
    }
}
