//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public long TeamId { get; set; }
        public string TeamName { get; set; }
        public string TeamSupervisor { get; set; }
        public string TeamLead { get; set; }
        public string TeamBackupLead { get; set; }
        public int TeamShift { get; set; }
        public int Company { get; set; }
        public int OfficeId { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> ModifiedDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string TeamType { get; set; }
    }
}
