//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME_SLOT_ASSIGNED_REASONS
    {
        public int Day_Id { get; set; }
        public string Time_Slot { get; set; }
        public long provider_code { get; set; }
        public long location_code { get; set; }
        public long practice_code { get; set; }
        public int Reason_id { get; set; }
        public bool Updated { get; set; }
    }
}
