//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsertaskAssigned
    {
        public long TASK_ID { get; set; }
        public string User_Id { get; set; }
        public Nullable<bool> Checklist { get; set; }
        public string Task_Discription { get; set; }
        public string Allowed_task_Units { get; set; }
        public string Allocated_Percentage { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Weighted_Average { get; set; }
    }
}
