//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTBL_EnrollmentTracker
    {
        public long ENROLLMENTTRACKER_ID { get; set; }
        public Nullable<long> PRACTICE_CODE { get; set; }
        public Nullable<long> PROVIDER_CODE { get; set; }
        public Nullable<long> PAYER_ID { get; set; }
        public string ENROLLMENT_TYPE { get; set; }
        public string ENROLLMENT_STATUS { get; set; }
        public Nullable<System.DateTime> FORM_RECEIVEDDATE { get; set; }
        public Nullable<System.DateTime> FORM_SENDDATE { get; set; }
        public string FORM_SENDTHROUGH { get; set; }
        public string TRACKING_NO { get; set; }
        public Nullable<System.DateTime> COMPLETION_DATE { get; set; }
        public string ENROLLMENT_REMARKS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<bool> DELETED { get; set; }
    }
}
