//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Value_Added_Services
    {
        public string Practice_Code { get; set; }
        public string Electronic_Lab { get; set; }
        public string E_Prescribe { get; set; }
        public string Kiosk { get; set; }
        public string Eligibility { get; set; }
        public string Web_Pro { get; set; }
        public string Call_Pro { get; set; }
        public string Transcription { get; set; }
        public string Toll_Free { get; set; }
        public string Education { get; set; }
        public string emr { get; set; }
        public string PHR { get; set; }
        public string BRC { get; set; }
        public string WELLNESSREMINDER { get; set; }
        public string FLUSHOTREMINDER { get; set; }
        public string FAX { get; set; }
    }
}
