//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XMLDOC
    {
        public long XMLDOCID { get; set; }
        public string TRACEID { get; set; }
        public Nullable<long> PATIENTACCOUNT { get; set; }
        public Nullable<long> POLICYNO { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public string INSURANCENAME { get; set; }
        public Nullable<long> PAYERID { get; set; }
        public string Pri_Sec_Oth_Type { get; set; }
        public string FILEPATH { get; set; }
        public Nullable<bool> LINKINGSTATUS { get; set; }
        public string ELIGIBILITYSTATUS { get; set; }
        public string XMLFILE { get; set; }
    }
}
