//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zip_state
    {
        public string zip_code { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> client_date_created { get; set; }
        public string modified_user { get; set; }
        public Nullable<System.DateTime> client_date_modified { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
